INSERT INTO projects (name, description, account) VALUES
('SP_IMP36', 'IICC Dwarka - Firewall System-230051', 'Larsen & Toubro Limited (Delhi)'),
('DC_CON40', 'Services for ReilTel Solar Structure-SC', 'RailTel Corporation of India Ltd.(Hyd)'),
('SI_SUP136', '"CHEIFNET HO location SD-WAN DEIVCE', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC6', '1 year SOC BIOLOGICAL E', 'BIOLOGICAL E. LIMITED'),
('CPSO86', '230042', 'Mak Controls and Systems Pvt Ltd'),
('SI_SUP1', '230043', 'C P AQUACULTURE (INDIA) PRIVATE LIMITED'),
('CPSO44', '230045', 'C P F (INDIA) PRIVATE LIMITED (AP)'),
('SI_SUP3', '230047', 'C P F (INDIA) PRIVATE LIMITED (AP)'),
('SI_SUP4', '230082', 'Larsen & Toubro Limited (Maharashtra)'),
('EA_IMP2', '230121 - BIAL IOT Bells and Veils', 'Bangalore International Airport Limited'),
('CPSO103', '230131', 'Center for Brain Research'),
('SI_IMP16', '230143', 'Larsen & Toubro Limited (Telangana)'),
('SI_IMP17', '230148 -  SONICWALL Firewall_HCS', 'Larsen & Toubro Limited (Telangana)'),
('SI_IMP34', '230172 - Space Telelink - Implementation', 'SPACE TELELINK LIMITED'),
('SI_IMP18', '230175 - Autocratic- FG600E', 'Autocratic Technology Private Limited'),
('SI_SUP29', '230188 - L&T_Supply of FG 100F', 'Larsen & Toubro Limited (Tamilnadu)'),
('SI_IMP19', '230264 - Zimbra license config_MSC', 'Larsen & Toubro Limited (Uttar Pradesh)'),
('SI_SUP36', '230291 - AEH - Supply (HP208)-4 Nos', 'GOVEL TRUST Aravind Eye Hospitals,'),
('SI_IMP10', '230317 - IIMK Wty Onsite Support', 'Indian Institute of Management (Kozhikode)'),
('SI_SUP62', '230354 - Supply of Fortinet FW 60F', 'C P F (INDIA) PRIVATE LIMITED (AP)'),
('SI_IMP13', '230358 - VLink SipCOT', 'V Link Systems (P) Ltd'),
('SI_SUP61', '230362', 'SPACE TELELINK LIMITED'),
('SI_SUP60', '230366 - Adobe Acrobat Std DC for teams', 'SPACE WORLD GROUP LLP'),
('SI_O-M11', '230442 - Vizag Smt Cty_Firewall Renewal', 'Larsen & Toubro Limited (Andhra Pradesh)'),
('CPSO362', '230471', 'Center for Brain Research'),
('SI_IMP35', '230478 - Ranext_Implementation_100F', 'RANEXT TECHNOLOGIES PRIVATE LIMITED'),
('SI_AMC25', '230531-Cethar Email Hosting', 'CETHAR ENERGY LIMITED'),
('SI_AMC26', '230532-Cethar Email Hosting', 'CETHAR ENERGY LIMITED'),
('SI_SUP57', '230545 - K7 Server supply', 'K7 Computing Private Limited'),
('SI_AMC29', '230559-Rossi Fortinet Firewall Renewal', 'Rossi Gearmotors (India) Pvt Ltd'),
('SI_AMC30', '230560-Rossi ILL', 'Rossi Gearmotors (India) Pvt Ltd'),
('SI_AMC31', '230561 - Siemens Energy Server AMC', 'SIEMENS ENERGY INDUSTRIAL TURBOMACHINERY INDIA PRIVATE LIMIT'),
('SI_O-M13', '230575-Flowserve Splicing', 'Flowserve India Controls Pvt Ltd'),
('SI_O-M14', '230593 - Flowserve Man power', 'Flowserve India Controls Pvt Ltd'),
('SI_SUP66', '230595 - KIOT supply', 'Knowledge Institute of Technology Trust'),
('SI_AMC33', '230602-Gajananda Webhosting', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SUP25', '230611', 'VOICE SNAP SERVICES PVT LTD'),
('SI_SUP67', '230631 VLink SFP Module supply', 'V Link Systems (P) Ltd'),
('SI_O-M27', '230633 - O_M Support & License renewal', 'Bangalore International Airport Limited'),
('CL_NEW_SUB4', '230636 - ReadyLink BulkMail Qty.25000', 'Readylink Internet Services Limited'),
('SI_O-M15', '230637-Flowserve Avaya work', 'Flowserve India Controls Pvt Ltd'),
('SI_SUP68', '230643 - Elgi ACP IP Phone', 'Elgi Equipment Limited'),
('SI_IMP49', '230653 - Rel Jio_A10 Deployment_Mumbai', 'RELIANCE PROJECTS & PROPERTY MANAGEMENT SERVICES LIMITED'),
('SI_SUP69', '230655 - Malnad HDD Supply', 'Malnad College of Engineering'),
('SI_AMC41', '230666 - Malnad College of Engineerin', 'Malnad College of Engineering'),
('SI_IMP45', '230670-KELTRON', 'Kerala State Electronics Development Corporation Ltd'),
('SI_AMC36', '230673-Elgi ACP AMC', 'Elgi Equipment Limited'),
('SI_SUP73', '230682-ZF Projector supply', 'ZF Wind Power Coimbatore Ltd'),
('SI_AMC37', '230685-Dimexion Firewall Renewal', 'Dimexon Diamonds Ltd'),
('SI_AMC40', '230699-LCC AMC', 'Lakshmi Card Clothing Mfg Company'),
('SI_IMP47', '230719-Rossi Gears Passive', 'Rossi Gearmotors (India) Pvt Ltd'),
('SI_AMC38', '230725- MRPL Support', 'Mangalore Refinery and PetrochemicalsLtd'),
('SI_AMC39', '230727-Olam Extreme AMC', 'Olam Information Services Private Ltd'),
('SI_AMC42', '230745-US TECHNOLOGY INTL. PVT. LTD', 'US TECHNOLOGY INTL. PVT. LTD'),
('SI_SUP77', '230746-Flowserve Cable supply', 'Flowserve India Controls Pvt Ltd'),
('SI_IMP50', '230754-KUDS AI order', 'KERALA UNIVERSITY OF DIGITAL SCIENCES, INNOVATION AND TECHNO'),
('SI_CON3', '230759-ZF Cisco Zoro Inspection', 'ZF Wind Power Coimbatore Ltd'),
('SI_IMP54', '230785-Tanfinet-Sterlite', 'Sterlite Technologies Limited'),
('SI_IMP52', '230788-Dormakaba Passive work', 'DORMAKABA INDIA PRIVATE LIMITED'),
('SI_IMP53', '230803-Olam Switches & AP Imp', 'Olam Information Services Private Ltd'),
('SI_AMC43', '230811-Aditi Tech', 'Aditi Tech Consulting Private Limited'),
('SP_O-M3', '230819 - T-Fiber O&M (Onsite support)', 'Larsen & Toubro Limited (Telangana)'),
('SI_SUP81', '230825-Olam Patch cord supply', 'Olam Information Services Private Ltd'),
('SI_IMP60', '230839-Catalist360', 'Catalist360'),
('SI_AMC45', '230851-GKB vision', 'GKB VISION PVT LTD'),
('SI_AMC46', '230907 - Citrix', 'Citrix R & D India P Ltd'),
('SI_CON5', '230915-Flowserve OTC', 'Flowserve India Controls Pvt Ltd'),
('SI_SUP85', '230920- VLink SFP Module supply', 'V Link Systems (P) Ltd'),
('SI_AMC47', '230927 - Siemens', 'SIEMENS ENERGY INDUSTRIAL TURBOMACHINERY INDIA PRIVATE LIMIT'),
('SI_CON6', '230935-SSMET', 'SSM Instuite of Engineering & Technology'),
('SI_IMP65', '230938-BEL Backup solution', 'BHARAT ELECTRONICS LTD'),
('SI_AMC48', '230945 - Aditi Tech', 'Aditi Tech Consulting Private Limited'),
('SI_SUP93', '230955- VLink Module supply', 'V Link Systems (P) Ltd'),
('SI_IMP75', '230963', 'QUALITY CARE HOSPITAL INDIA LTD Vizag-1'),
('SI_IMP74', '230968', 'RAMKRISHNA CARE MEDICAL SCIENCES PRIVATE LIMITED'),
('SI_AMC49', '230970-Elgi Motor Plant AMC', 'Elgi Equipment Limited'),
('SI_IMP67', '230975-SRS IIT Palakkad UPS Supply', 'Sukhdev Raj Sharma Engineers & Contractors Pvt Ltd'),
('SI_SUP96', '240015-Amrita Kollam Palo Alto', 'Amrita Vishwa Vidyapeetham(KL)'),
('SI_SUP97', '240018-Jos Alukkas Thin Client', 'Alukkas Enterprises Private Limited'),
('SI_CON7', '240020 - Rathinam consultancy', 'K.Palaniyappa Memorial Educational Trust'),
('SI_SUP99', '240022-ZF Passive material supply', 'ZF Wind Power Coimbatore Ltd'),
('SI_SUP98', '240029-Vlink SFP module supply', 'V Link Systems (P) Ltd'),
('SI_AMC50', '240030- Citrix R & D India Pvt. Ltd', 'Citrix R & D India P Ltd'),
('SI_IMP83', '240032-Dimexon OTC', 'DIMEXON INTEGRATED BUSINESS SERV PVT LTD Mumbai'),
('SI_AMC51', '240035-MNEC CONSULTANTS PRIVATE LIMITED', 'MNEC CONSULTANTS PRIVATE LIMITED'),
('SI_AMC52', '240042 - Defense Services Staff College', 'DEFENCE SERVICES STAFF COLLEGE'),
('EA_IMP9', '240047-ENES Tex', 'M/S. ENES TEXTILE MILLS'),
('SI_AMC53', '240049-SecOnCloud IT Services-BIOCON', 'SecOnCloud IT Services Pvt. Ltd'),
('SI_O-M23', '240053 - Bangalore International Airport', 'Bangalore International Airport Limited'),
('SI_IMP87', '240054-Govt Adi Firewall', 'Govt. Adi dravidar Welfare Higher Secondary school'),
('SI_IMP85', '240056- Rabwin Switch', 'RABWIN INDUSTRIES PVT LTD'),
('SI_IMP82', '240057 - MCET-Passive IMP', 'Dr. Mahalingam College of Engineering and Technology'),
('SI_IMP86', '240059-Rossi Gears CCTV & VC Imp', 'Rossi Gearmotors (India) Pvt Ltd'),
('SI_O-M24', '240060-AIIMS GORAKHPUR', 'Larsen & Toubro Limited (Uttar Pradesh)'),
('SI_O-M25', '240071- BGPPL - O&M', 'BILT GRAPHIC PAPER PRODUCTS LIMITED- HARYANA'),
('SI_IMP89', '240078-KSEB Firewall Installation', 'Kerala State Electricity Board Limited'),
('SI_AMC56', '240079 - Royal Sundaram general ins. Ltd', 'Royal Sundaram General Insurance Co. Limited'),
('SI_AMC59', '240095- K.Palaniyappa Memorial Trust', 'K.Palaniyappa Memorial Educational Trust'),
('SI_AMC57', '240103-TAMILNADU INVESTMENT CORPORATION', 'THE TAMILNADU INVESTMENT CORPORATION LTD'),
('SI_IMP94', '240112 - BIAL - PM_WANI & Router', 'Bangalore International Airport Limited'),
('SI_AMC60', '240115-BIAL, CISCO EA SUBSCRIPTION SNT', 'Bangalore International Airport Limited'),
('SI_IMP92', '240119-MCET Active order', 'Dr. Mahalingam College of Engineering and Technology'),
('SI_AMC61', '240122_Royal Sundaram General Insurance', 'Royal Sundaram General Insurance Co. Limited'),
('SI_AMC62', '240129-NINESTAR MOTORCYCLES-PALO ALTO', 'NINESTAR MOTORCYCLES (BANGALORE) PRIVATE LIMITED'),
('SI_IMP96', '240133-MCET Netgear order', 'Dr. Mahalingam College of Engineering and Technology'),
('SI_AMC63', '240139 - Readylink Internet Services', 'Readylink Internet Services Limited'),
('SI_SUP103', '240144-Elgi IP Phone supply', 'Elgi Equipment Limited'),
('SI_SUP104', '240147 - Vlink Module supply', 'V Link Systems (P) Ltd'),
('SI_AMC66', '240151 - AMC of Switches & Routers', 'Lakshmi Card Clothing Mfg Company'),
('SI_IMP98', '240163 - BH_COPC wifi & Passive comp', 'Quality care India Limited-Telangana'),
('SI_IMP99', '240164 - BBSR_Active & Passive comp_SITC', 'Quality Care India Limited- Orissa'),
('SI_IMP100', '240169 - Indore_Active comp (AP)_SITC', 'Convenient Hospitals Ltd'),
('SP_SUP8', '240172 - Supply of Redhat_Linux_APSFL', 'Larsen & Toubro Limited (Andhra Pradesh)'),
('SI_IMP101', '240175-Artika cotton Mills', 'ARTIKA COTTON MILLS (A UNIT OF ENES TEXTILE MILLS)'),
('SI_IMP102', '240177-Rabwin DHCP & AD', 'RABWIN INDUSTRIES PVT LTD'),
('SI_IMP103', '240181-GKNM WiFi order', 'THE KUPPUSWAMY NAIDU CHARITY TRUST FOR EDUCATION AND MEDICAL'),
('SI_SUP108', '240189 - BIT Sathy Firewall supply', 'BANNARIAMMAN EDUCATIONAL TRUST'),
('SI_SUP109', '240191 - VLink - Module supply', 'V Link Systems (P) Ltd'),
('SI_IMP113', '240212- IT', 'Netcon Technologies Private Limited'),
('SI_SUP110', '240217 - Visteon - Cisco AP supply', 'VISTEON ELECTRONICS INDIA PRIVATE LTD'),
('SI_SUP112', '240218 - Supply of FortiGate switches', 'Larsen & Toubro Limited (Andhra Pradesh)'),
('SI_SUP111', '240220_Supply_Fortigate POE switch', 'Larsen & Toubro Limited (Andhra Pradesh)'),
('FIELD_IMP3', '240223_ITMS_Chennai_Field_IMP3', 'L&T Technology Services Limited'),
('SI_PROF_SER7', '240231- Rossi Gears', 'Rossi Gearmotors (India) Pvt Ltd'),
('SI_AMC68', '240238 - Rossi Gears Firewall Renewal', 'Rossi Gearmotors (India) Pvt Ltd'),
('SI_SUP113', '240298 - MAK Controls supply', 'Mak Controls and Systems Pvt Ltd'),
('SI_IMP105', '240302-MCET Switch & Module addl qty', 'Dr. Mahalingam College of Engineering and Technology'),
('SI_IMP106', '240329-GKNM IPPBX Supply Installation', 'THE KUPPUSWAMY NAIDU CHARITY TRUST FOR EDUCATION AND MEDICAL'),
('DC_AMC7', '240345 CAMC of Non IT DR Infra', 'Regional Cancer Centre'),
('SI_SUP121', '240349 - MAPAL - Supply of Patch cords', 'MAPAL India Private Limited'),
('SI_SUP120', '240354', 'Royal Sundaram General Insurance Co. Limited'),
('SI_SUP117', '240364 - SentinelOne Endpoint Solution', 'McFadyen Consulting Software India (P) Ltd'),
('SI_O-M29', '240390 L2 Onsite Support', 'Elgi Equipment Limited'),
('SI_O-M30', '240397 NMDC O&M', 'NMDC Ltd-(Hyderabad)'),
('SI_AMC70', '240398', 'Royal Sundaram General Insurance Co. Limited'),
('SI_IMP109', '240405 - SITC Palo Alto FW -3nos', 'McFadyen Consulting Software India (P) Ltd'),
('FIELD_IMP4', '240411', 'Larsen & Toubro Limited (Telangana)'),
('SI_PROF_SER10', '240421 - Fortinet FW Subs. Renewal', 'Dimexon Diamonds Ltd'),
('CPSO625', '240428 - Rapid 7 Subsc. Renewal', 'BIOLOGICAL E. LIMITED'),
('SI_AMC72', '240430 - AMC of Cisco Switches & Routers', 'Lakshmi Card Clothing Mfg Company'),
('SI_SUP124', '240441_Visteon_Supply of Cisco 9200 48P', 'VISTEON ELECTRONICS INDIA PRIVATE LTD'),
('SI_IMP114', '240443 - Malnad College Firewall Upgrade', 'Malnad College of Engineering'),
('SI_IMP115', '240447 - Rossi Gears Passive work', 'Rossi Gearmotors (India) Pvt Ltd'),
('SI_O-M31', '240448 - ARC Support for 2 years', 'PETRONET LNG LIMITED'),
('CL_SUP27', '240451- Cloud PAM', 'McFadyen Consulting Software India (P) Ltd'),
('SI_IMP117', '240462-SSN-SITC-Smart Rack Commissioning', 'SHIV NADAR UNIVERSITY'),
('SI_AMC73', '240466-CAMC for CISCO CORE SWITCH', 'G.Kuppuswamy Naidu Memorial Hospital'),
('CPSO632', '240471', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_SUP125', '240478-CHIEFNET SECURE SDWAN NETWORK', 'GAJAANANDA JEWELLERY MAART INDIA PVT LTD - HYDERABAD'),
('SI_SUP126', '240479-CHIEFNET SECURE SDWAN NETWORK', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_SUP127', '240481-CHIEFNET SECURE SDWAN NETWORK', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_SUP128', '240483-CHIEFNET SECURE SDWAN NETWORK', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_SUP129', '240486-CHIEFNET SECURE SDWAN NETWORK', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_SUP130', '240487-CHIEFNET SECURE SDWAN NETWORK', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_SUP131', '240488-CHIEFNET SECURE SDWAN NETWORK', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_SUP132', '240490-CHIEFNET SECURE SDWAN NETWORK', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_SUP133', '240492 - CHIFNET', 'Gajaananda Jewellery Mart India P Ltd'),
('CPSO643', '240494', 'Mak Controls and Systems Pvt Ltd'),
('SI_AMC74', '240496 - AMC of Dell Server', 'CD Technotex LLP'),
('DC_AMC9', '240498 - 4th yr AMC of DC & DR (Non IT)', 'Wipro GE Healthcare Private Limited'),
('SI_SUP134', '240499 - Wipro GE (SRH)', 'Wipro GE Healthcare Private Limited'),
('SI_IMP119', '240504-malnad-Cisco switches & Rucker AP', 'Malnad College of Engineering'),
('SI_SUP135', '240508 - Wireline - Arista Switch supply', 'WIRELINE SOLUTION INDIA PVT LTD'),
('SI_IMP118', '240514-AIIMS , Delhi', 'All India Institute of Medical Sciences (AIIMS)'),
('SI_AMC75', '240532 - Trendmicro License Renewal', 'TVM Signalling and Transportation Systems Pvt Ltd'),
('SP_AMC12', '240534-Service Renewal_A10 Load Balancer', 'Larsen & Toubro Limited (Telangana)'),
('MS_CLOUD9', '240540', 'TRIVITRON HEALTH CARE'),
('SI_PROF_SER12', '240542 - Webserver Hosting', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_SUP138', '240544 - CHIEFNET SD-WAN DEVICE CHARGES', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_IMP125', '240562 -Rabwin CCTV', 'RABWIN INDUSTRIES PVT LTD'),
('SI_SUP140', '240577 - Rathnam College', 'K.Palaniyappa Memorial Educational Trust'),
('SI_SUP139', '240585-Elgi WiFi AP Order', 'Elgi Equipment Limited'),
('SI_IMP129', '240586', 'Amnex Infotechnologies Private Limited'),
('SI_SUP142', '240600 - NPST -  NGFW Supply', 'NATIONAL PENSION SYSTEM TRUST'),
('SI_SUP141', '240604 -MCE additional switch supply', 'Malnad College of Engineering'),
('SI_SUP143', '240620 - Manipal Hospital Jayanagar', 'Manipal Health Enterprises Pvt Ltd.'),
('SI_SUP144', '240621-Manipal hospital Malleshwaram', 'Manipal Health Enterprises Pvt Ltd.'),
('SI_SUP145', '240623 -Manipal Hospital  Mysore', 'MANIPAL HOSPITALS PRIVATE LIMITED'),
('SI_SUP146', '240625-Manipal Hospital Shanthinikethan', 'Manipal Health Enterprises Pvt Ltd'),
('SP_PROF_SER5', '240651 HPC Reconfiguration', 'Central Marine Fisheries Research Inst.'),
('SI_SUP147', '240655 - DSSC Switch supply', 'DEFENCE SERVICES STAFF COLLEGE'),
('SI_IMP131', '240656 - RIL - A10 device Installation', 'Reliance Industries Limited'),
('DC_CON33', '240662 - Cisco Advance Services.', 'Larsen & Toubro Limited (Telangana)'),
('SI_IMP135', '240667 - KSR College Firewall', 'K S Rangasamy College of Technology (Autonomous)'),
('SI_IMP134', '240672-BSES', 'BSES Yamuna Power Limited'),
('SI_IMP137', '240679 - SRS - NIT Surathkal', 'Sukhdevraj Sharma Engineers & Contractors Pvt Ltd.'),
('SI_O-M32', '240680 - O&M ITPL 1 year', 'India Trimmings Pvt Ltd'),
('SI_SUP149', '240683 - Solugenix Sonic FW supply', 'Solugenix India Private Limited'),
('SI_IMP136', '240687 -  Elgi Core Switch order', 'Elgi Equipment Limited'),
('SI_SUP150', '240691 - Pallava Group Switch Supply', 'PALLAVA TEXTILES (P) LIMITED (Sri Cheran - Unit S1)'),
('CPSO701', '250002 - Radware WAF Renewal', 'Siemens Technology and Services Pvt Ltd.'),
('SI_AMC78', '250006 - AMC of HP Server Infra', 'Siemens Limited (Maharashtra)'),
('SI_AMC79', '250009 - AMC of Infra Devices', 'Siemens Limited (Maharashtra)'),
('SI_SUP151', '250012 - Mak Control CCTV Supply', 'Mak Controls and Systems Pvt Ltd'),
('SI_SUP157', '250014', 'Manipal Health Enterprises Pvt. Ltd.'),
('SI_SUP153', '250021', 'AMRI Hospitals Ltd - East Office'),
('SI_SUP155', '250023 - AMRI - WI-Fi_Execution(AP9166)', 'AMRI Hospitals Ltd - East Office'),
('SI_AMC81', '250024-AMC IBM servers & Hitachi Storage', 'Siemens Energy Industrial Turbomachinery India Pvt. Ltd'),
('SI_AMC84', '250025 - HP Server AMC 2No 3Y', 'Siemens Limited (Maharashtra)'),
('SI_AMC80', '250026 - AMC OF SAN Switches', 'US TECHNOLOGY INTL. PVT. LTD'),
('SI_IMP140', '250028 - Pallava grp One time impl', 'PALLAVA TEXTILES (P) LIMITED (Sri Cheran - Unit S1)'),
('MS_SEC10', '250029 - Chiefnet support renewal erode', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC11', '250030 - Chiefnet support renewal CBE', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC12', '250031 - Chiefnet support renewal NMKL', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC13', '250032 - Chiefnet Support Renewal MDU', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC15', '250033 - Chiefnet support renewal - Slm', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC16', '250034 - Chiefnet support renewal Rjplym', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC14', '250035 - Chiefnet support renewal Hyd', 'GAJAANANDA JEWELLERY MAART INDIA PVT LTD - HYDERABAD'),
('MS_SEC17', '250036 Chiefnet Support Renewal vrdchlm', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_PROF_SER14', '250037 - Extreme Premier support renewal', 'Dr K M Cherian Institute of Medical Sciences Private Limited'),
('SI_SUP154', '250042 - Hirotec Coimbatore', 'Hirotec India Private Limited'),
('SI_SUP166', '250043 - Siemens', 'Siemens EDA (India) Private Limited'),
('SI_AMC82', '250046 - AMC of IBM server & Storage', 'SIEMENS ENERGY INDUSTRIAL TURBOMACHINERY INDIA PRIVATE LIMIT'),
('SI_SUP161', '250051', 'Manipal Health Enterprises Pvt. Ltd.'),
('SI_SUP164', '250052', 'Manipal Health Enterprises Pvt Ltd.'),
('SI_SUP159', '250054', 'Manipal Hospital Dwarka Pvt. Ltd'),
('SI_SUP162', '250055', 'Manipal Health Enterprises Pvt Ltd.'),
('SI_SUP165', '250056', 'Manipal Health Enterprises Pvt. Ltd.'),
('SI_SUP163', '250057', 'MANIPAL HOSPITALS PRIVATE LIMITED'),
('SI_SUP160', '250058', 'Manipal Hospital Dwarka Pvt. Ltd'),
('SI_SUP158', '250059', 'Manipal Health Enterprises Pvt Ltd.'),
('SI_SUP156', '250060 - Hirotec Pune', 'Hirotec India Private Limited'),
('SI_AMC83', '250061 - Juniper switch Support renewal', 'Mane India Private Limited (Telangana)'),
('SI_IMP141', '250067 - SIMS', 'Saraswathi Institute of Medical Sciences'),
('SI_O-M33', '250068 - AMC & O&M for Cisco Stack', 'Indian Institute of Management (Kozhikode)'),
('SI_SUP168', '250071 - Supply of Meraki with 5 Yrs lic', 'Manipal Health Enterprises Pvt Ltd.'),
('SI_IMP143', '250072 - TN School', 'KS SMART SOLUTIONS PRIVATE LIMITED'),
('SI_IMP142', '250074 - Pricol Passive order', 'Pricol Limited'),
('SI_AMC85', '250084 - HP Care pack 5710 switches', 'L.G.BALAKRISHNAN & BROS LIMITED NAGPUR PLANT - ICD'),
('SI_IMP144', '250086 - Pricol - Tray work', 'Pricol Limited'),
('SP_O-M4', '250087 - IVRS L2 Support', 'Bangalore International Airport Limited'),
('SI_AMC86', '250088 - AMC of DC IT Items', 'Mahanagar Telephone Nigam Limited-Delhi'),
('SI_AMC87', '250104 - LCC Zimbra Cloud Renewal', 'Lakshmi Card Clothing Mfg Company'),
('SI_SUP169', '250108 - IBS Software', 'IBS Software Private Limited'),
('SI_SUP171', '250109 - SI of HI Tech Lab Materials', 'Larsen & Toubro Limited (Tamilnadu)'),
('SI_AMC88', '250113 - Firewall AMC Renewal Support', 'THE TAMILNADU INVESTMENT CORPORATION LTD'),
('SI_IMP147', '250115 - Malnad - OTC Charges', 'Malnad College of Engineering'),
('SI_SUP170', '250116 - Supply of Commvault License', 'Cochin International Airport Limited'),
('MS_SEC20', '250120 -Chiefnet Sdwan Support - Bhavani', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC21', '250121 - Chiefnet SDwan Support charges', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC19', '250122 - Chiefnet SDWAN Support charges', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC22', '250123 - Chiefnet SDwan Support Permblur', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC23', '250124-Chiefnet SDwan Support Gbichtiplm', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC24', '250125 - Chiefnet SDwan Support Satymglm', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC25', '250126 - Chiefnet SDwan Support Harur', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC26', '250127 - Chiefnet SDwan Support virdungr', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC27', '250128 -Chiefnet SDwan Support tiruvnmla', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC18', '250129 - Chiefnet SDWAN Charges - Hyd', 'GAJAANANDA JEWELLERY MAART INDIA PVT LTD'),
('SI_O-M34', '250130 - AIIMS O&M_AMC', 'All India Institute of Medical Sciences'),
('SI_AMC89', '250132 - Meraki Support renewal - 3Y', 'NRD TECH PRIVATE LIMITED'),
('SI_IMP146', '250133 - RSAL STEEL', 'RSAL STEEL PRIVATE LIMITED'),
('SI_AMC90', '250152 - LAN Network AMC', 'Indian Institute Of Information Technology and Management Ke'),
('DC_IMP31', '250153 - Aquasub DC work', 'AQUASUB ENGINEERING'),
('DC_AMC10', '250155 - Server Room Non IT Infra AMC', 'Indian Institute of Management (Kozhikode)'),
('SI_PROF_SER16', '250157-Thunder ADC Software Flex Renewal', 'Medi Assist Healthcare service Limited'),
('SI_SUP173', '250162 - Pioneer', 'Pioneer One Consulting LLP Limited'),
('SI_PROF_SER17', '250163 - Fortinet FW Renewal', 'Lakshmi Card Clothing Mfg Company'),
('CPSO753', '250166 - Glasstile Prog kit Supply&Trai', 'Bangalore International Airport Limited'),
('DC_IMP32', '250167- Plumira contractors - Pricol', 'Plumeria Contracting Services'),
('SI_PROF_SER18', '250168 - Zimbra Email Services', 'Readylink Internet Services Limited'),
('SI_SUP174', '250171 - Hirotec license supply', 'Hirotec India Private Limited'),
('SI_SUP175', '250173 - SI of Switch and LAN points', 'The Marine Products Export Development'),
('SI_AMC91', '250183 - MCET SSL Certificate renewal', 'Dr. Mahalingam College of Engineering and Technology'),
('SI_PROF_SER19', '250185 - ATS of Radware Altean ADC/LLB', 'Centre for Railway Information Systems'),
('SI_SUP176', '250186 - IIT Palakkad -Patch Panel', 'Indian Institute of Technology Palakkad'),
('SI_AMC92', '250187 - Cisco Switches AMC', 'BHARAT PETROLEUM CORPORATION LIMITED'),
('SI_AMC93', '250190 - AMC for HP Tape Library', 'Siemens Healthcare Private Limited'),
('SI_AMC94', '250192 - AMC Renewal of Cisco', 'Royal Sundaram General Insurance Co. Limited'),
('SI_SUP178', '250194 - ITCOT Core Switch', 'SGS Electronics'),
('SI_AMC95', '250195 - Fortinet 30E for 1yr', 'Dimexon Jewellery Creations Pvt Ltd'),
('SI_IMP149', '250196 - One Time Execution_AP&Meraki FW', 'Manipal Health Enterprises Pvt Ltd.'),
('SP_AMC13', '250197 - CAMC of Avaya EPABX', 'Flowserve India Controls Pvt Ltd'),
('SP_O-M5', '250199 - PMWANI Support & O_M', 'Bangalore International Airport Limited'),
('SI_SUP179', '250200 - GKNM Analog phone IP adpater', 'G.Kuppuswamy Naidu Memorial Hospital'),
('SI_IMP150', '250203 - LGB Server Room Dressing', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_IMP154', '250213 - AMRI - WiFI Implementation', 'Manipal Hospital (East) India Limited'),
('SI_IMP151', '250217-CRI Pumps Temperature monitor', 'C.R.I.PUMPS PRIVATE LIMITED'),
('DC_AMC11', '250219 - Compressor service charges', 'Larsen & Toubro Limited (Uttar Pradesh)'),
('SI_SUP107', '250221 - FortiGate Renewal', 'Bangalore International Airport Limited'),
('CPSO99', '250223 - Vizag O&M', 'Larsen & Toubro Limited (Andhra Pradesh)'),
('SI_IMP152', '250224 - LGB New office work', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('MS_SEC28', '250227 - Fortinet FW Support Renewal', 'BK POWER'),
('SI_IMP153', '250230 - Pricol Outdoor Camera work', 'Pricol Limited'),
('SI_SUP181', '250232 - Siemens License supply', 'Siemens Technology and Services Pvt Ltd.'),
('SI_SUP180', '250234 - KMCherian Extreme supply', 'Dr K M Cherian Institute of Medical Sciences Private Limited'),
('SI_SUP184', '250236 - Olam Agri UTP Patch Cords', 'Olam Agri Business Services India Private Limited'),
('SI_IMP158', '250238/39/41/42/43-CRI-Tempsensor', 'C.R.I.PUMPS PRIVATE LIMITED'),
('EA_IMP10', '250244 - ENES Additional work order', 'M/S. ENES TEXTILE MILLS'),
('MS_SEC29', '250245 - Chiefnet SDWAN Support, Dmapuri', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC45', '250246-Chiefnet SDWAN Support, Kukatplly', 'GAJAANANDA JEWELLERY MAART INDIA PVT LTD'),
('MS_SEC30', '250247 Chiefnet SDWAN Support,Tvnamalai', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC31', '250248 - Chiefnet SDWAN Support,Udmlpet', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC32', '250249-Chiefnet SDWAN Support,  CBE', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC33', '250250-Chiefnet SDWAN Support - Erode', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC34', '250251-Chiefnet SDWAN Support - Madurai', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC35', '250252-Chiefnet SDWAN Support, Namakkal', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC36', '250253-Chiefnet SDWAN Support, Rajaplyam', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC37', '250254-Chiefnet SDWAN Support,- Permblur', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC38', '250255-Chiefnet SDWAN Support - Bhavani', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC39', '250256-Chiefnet SDWAN Support, Gbiciplym', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC40', '250257-Chiefnet SDWAN Support- HO Avnshi', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC41', '250258-Chiefnet SDWAN Support.Sthamnglm', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC42', '250259-Chiefnet SDWAN Support,Virdhnagar', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC43', '250260-Chiefnet SDWAN Support,Virdhchlm', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC44', '250261-Chiefnet SDWAN Support - Salem', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SEC46', '250262 - Chiefnet SDWAN Support, Medptnm', 'GAJAANANDA JEWELLERY MAART INDIA PVT LTD'),
('SI_SUP182', '250263 - Icare Supply order', 'I Care'),
('CL_NEW_SUB5', '250272-Ready Link Microsoft O365', 'Readylink Communication and Services'),
('SI_SUP185', '250274 - LGB Annur Wifi', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_O-M35', '250277- Rossi ILL Renewal', 'Rossi Gearmotors (India) Pvt Ltd'),
('FIELD_O-M10', '250282 - ON Call Support - IGH Delhi', 'Larsen & Toubro Limited (Delhi)'),
('SI_IMP161', '250283 - Pricol CCTV Installation', 'Pricol Limited'),
('SI_IMP160', '250292 - NMS Global Ventures', 'NMS Globl Ventures'),
('SI_IMP163', '250293 - Delphi TVS', 'Delphi-TVS Technologies Limited'),
('SI_IMP162', '250295 - Ashok Leyland Sriperumbudur', 'ASHOK LEYLAND LTD.'),
('SI_AMC96', '250309 - Fortinet Firewall renewal', 'Rossi Gearmotors (India) Pvt Ltd'),
('SI_AMC97', '250312 - F5 LLB & SLB support Renewal', 'Bangalore International Airport Limited'),
('SI_SUP188', '250313 - KM Cherian Module supply', 'Dr K M Cherian Institute of Medical Sciences Private Limited'),
('SI_IMP167', '250318 - Innerspace IIMK Kochi', 'INNERSPACE.INC'),
('DC_AMC12', '250319 - AMC of DG, UPS, AC, Smart Rack', 'Larsen & Toubro Limited (Uttar Pradesh)'),
('SI_IMP164', '250321 - NMS global Venture AV system', 'NMS Globl Ventures'),
('SI_SUP189', '250322 - LGB Chennai - Wifi', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('DC_AMC13', '250326 - Datacenter Non IT AMC', 'SREE CHITRA TIRUNAL INSTITUTE FOR MEDICAL SCIENCES & TECHNOL'),
('SI_IMP166', '250327 - NMS Infra', 'NMS INFRAA'),
('DC_AMC14', '250333 - DC- Non IT Infra AMC - T-Fiber', 'Larsen & Toubro Limited (Telangana)'),
('SI_AMC98', '250334 - AMC of Switches & Routers', 'Lakshmi Card Clothing Mfg Company'),
('SI_O-M36', '250338 - Onsite L2 Engineer Support', 'Elgi Equipment Limited'),
('SI_AMC102', '250339 - Network AMC at Elgi ACP Plant', 'Elgi Equipment Limited'),
('SI_AMC99', '250341 - AMC of Network items -  Elgi HO', 'Elgi Equipment Limited'),
('SI_IMP169', '250342 - Mindsprint', 'Mindsprint Digital India PvtLtd'),
('SI_AMC100', '250343 - Network AMC -Elgi Bang/Foundry', 'Elgi Equipment Limited'),
('SI_AMC101', '250344 - Network AMC - Elgi Motor Plant', 'Elgi Equipment Limited'),
('SI_IMP168', '250345 - Elgi Blr CO', 'Elgi Equipment Limited'),
('CPSO760', '250375', 'Kiran Medical Systems'),
('SI_IMP171', '250381-Rossi Gears Network', 'Rossi Gearmotors (India) Pvt Ltd'),
('SI_AMC106', '250382 - Elgi Arista AMC', 'Elgi Equipment Limited'),
('SI_IMP172', '250384 - Elgi CO BLR VC Solution', 'Elgi Equipment Limited'),
('SI_IMP170', '250385 - Mindsprint Arista Switch', 'Mindsprint Digital India PvtLtd'),
('SI_AMC104', '250386 - Web Hosting Services', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_AMC105', '250393 - AMC of Meraki Switches', 'Checktronix India Private Ltd'),
('SI_IMP173', '250394 - Seyyon Firewall', 'Seyyone Software Solutions Pvt Ltd'),
('SI_IMP176', '250396 - RailTel AAI', 'RailTel Corporation of India Ltd.(Hyd)'),
('SI_PROF_SER22', '250398 - Extreme Support Renewal', 'Dr K M Cherian Institute of Medical Sciences Private Limited'),
('DC_AMC15', '250399 - DR Non IT Infra AMC', 'Regional Cancer Centre'),
('CL_SUB_RE7', '250401', 'TRIVITRON HEALTH CARE'),
('CPSO766', '250402', 'TRIVITRON HEALTH CARE'),
('SI_IMP174', '250404 - DSSC Switches installation', 'DEFENCE SERVICES STAFF COLLEGE'),
('SI_O-M37', '250405 - TN School O&M', 'KS SMART SOLUTIONS PRIVATE LIMITED'),
('SI_IMP175', '250406 -IIMK WiFi Network in Hostels', 'Indian Institute of Management (Kozhikode)'),
('SI_SUP193', '250413 - Mindssprit data cable supply', 'Mindsprint Digital India PvtLtd'),
('SI_IMP177', '250414 - Railway Site Survey', 'SEAMLESS COMMUNICATION SYSTEMS PVT LTD'),
('SI_IMP178', '250415 - CheifNet Platform for SDWAN', 'Infinite NETWORKS'),
('SI_IMP179', '250417_BIAL_T1_Upgrade_Fornet FW_SITC', 'Bangalore International Airport Limited'),
('SI_PROF_SER25', '250419 - Domain Renewal Charges', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_AMC108', '250420 - Non Comprehensive AMC 1 year', 'Center for Brain Research'),
('SI_IMP180', '250421 - Seamless Railway', 'SEAMLESS COMMUNICATION SYSTEMS PVT LTD'),
('SI_AMC107', '250422 - Server AMC', 'Siemens Limited (Maharashtra)'),
('SI_PROF_SER26', '250423 - Annual Contract N/w Specialist', 'Siemens Technology and Services Pvt Ltd.'),
('SI_O-M38', '250445 - Tfiber O&M', 'Larsen & Toubro Limited (Telangana)'),
('CL_NEW_SUB7', '250446', 'Future Generali India Insurance Company'),
('SI_O-M39', '250447 - L&T TFiber O&M', 'Larsen & Toubro Limited (Telangana)'),
('CL_NEW_SUB6', '250450', 'Future Generali India Insurance Company'),
('SP_SUP9', '260011 - Netcon Uganda- Acer|', 'Netcon Technologies Private Limited'),
('SI_O-M40', '260013 - ITPL Onsite support 2 engrs', 'India Trimmings Pvt Ltd'),
('SI_IMP182', '260014-ACP Plant WIFI - ELGI', 'Elgi Equipment Limited'),
('SI_AMC109', '260017_MAR_NW Sw_AMC_JAN''24 to Mar''25', 'Bangalore International Airport Limited'),
('SI_IMP183', '260019 - LGB Board Room VC Solution', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_SUP199', '260034 - Supply server Rack', 'Urban Desk Private Limited'),
('SI_PROF_SER27', '260035 O365 License Renewal', 'International Airport Hotels and Resorts'),
('DC_AMC16', '260043 - DC & DR Non IT AMC at MCC', 'Wipro GE Healthcare Private Limited'),
('MS_CLOUD10', '260044', 'Lakshmi Card Clothing Mfg Company'),
('SI_AMC110', '260045 - Firewall Support Renewal', 'THE TAMILNADU INVESTMENT CORPORATION LTD'),
('SI_SUP200', '260047 - IIT Bombay Power Supply', 'Indian Institute of Technology Bombay'),
('SI_AMC111', '260048 - HP support care renewal', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_IMP185', '260052-LGB-VIDEOWALL', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_SUP202', '260062_IITM Prvartak RAM upgrdation', 'IITM Pravartak Technologies Foundation'),
('SI_CON11', '260063 - Service fee for MMRDA project', 'CHAIN-SYS (INDIA) PRIVATE LIMITED'),
('MS_INFRA2', '260068 FCI (NOC/IOC)', 'Analog and Digital Labs India Pvt Ltd'),
('SI_SUP203', '260073- Hirotec Switch & Wifi Supply', 'Hirotec India Private Limited'),
('SI_AMC112', '260074 - DGX A100 AMC', 'Mahatma Gandhi University'),
('SI_IMP187', '260076 - Rossi Gears CCTV order', 'Rossi Gearmotors (India) Pvt Ltd'),
('SI_AMC113', '260077-Fortianalyzer Support Renewal LGB', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_IMP186', '260078 - NTPC Assessment LAN Infra', 'NTPC Limited - TL'),
('SI_PROF_SER28', '260080 Zimbra Email Support renewal', 'Readylink Internet Services Limited'),
('SI_AMC114', '260081-Firewall Support Renewal -1 year', 'Lakshmi Card Clothing Mfg Company'),
('SI_SUP204', '260083 - LGB Cabins Display Supply', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_IMP196', '260084 - SRS - CMET Thrissur', 'Sukhdevraj Sharma Engineers & Contractors Pvt Ltd.'),
('SI_SUP205', '260086 - LGB Aruba WiFi - Coimbatore', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_SUP206', '260087- LGB Aruba Wi-Fi-Bangalore', 'L.G.BALAKRISHNAN & BROS LIMITED'),
('SI_IMP188', '260091 - Elgi Accounts', 'Elgi Equipment Limited'),
('SP_SUP10', '260092-Malawi supply', 'Netcon Technologies Private Limited'),
('SP_IMP51', '260101 - Elgi Sauer -WiFi', 'ELGI SAUER COMPRESSORS LIMITED'),
('SI_IMP189', '260106 - GKNM Nursing college', 'G.Kuppuswamy Naidu Memorial Hospital'),
('SI_IMP190', '260109-Sai pooja-S&I of Firewall', 'Sai Pooja Travel Wings Private Limited'),
('EA_SUP2', '260111-HPE SFP Supply', 'All India Institute of Medical Sciences (AIIMS)'),
('SI_AMC115', '260112 - Firewall Support renewal', 'Kerala State Electricity Board Limited'),
('SI_IMP194', '260113 - SRS NIT Calicut', 'Sukhdevraj Sharma Engineers & Contractors Pvt Ltd.'),
('SI_SUP210', '260114 - LGB Aruba Switch Supply', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_IMP193', '260122-NMS Infra Passive active', 'NMS INFRAA'),
('SI_AMC116', '260123 - O365 License Renewal', 'Readylink Communication and Services'),
('SI_PROF_SER29', '260124 - SSL certificate renewal', 'Dr. Mahalingam College of Engineering and Technology'),
('SI_PROF_SER30', '260125 - Oracle Support', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_IMP195', '260128', 'CHAITANYA INDIA FIN CREDIT PVT LTD'),
('SI_O-M41', '260129-Rossi ILL', 'Rossi Gearmotors (India) Pvt Ltd'),
('SI_SUP212', '260130 - Tata Electronics', 'TATA ELECTRONICS PRIVATE LIMITED'),
('SI_IMP197', '260133 - ITCOT', 'ITCOT Limited'),
('SI_SUP211', '260136_INNSPARK Palo Alto', 'Innspark Solutions Private Limited'),
('SI_IMP198', '260137-RVNL', 'Rail Vikas Nigam Limited'),
('SI_IMP200', '260138', 'The Director,National Institute of Technology Tiruchirappall'),
('MS_SEC47', '260154 - Chiefnet support renewal', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_IMP199', '260155 - EA - 1Yr - Smartnet & Subscript', 'Bangalore International Airport Limited'),
('SI_O-M42', '260161 - Manpower support at T Fiber', 'V Link Systems (P) Ltd'),
('SP_AMC14', '260165 - Cloudera Support renewal', 'L&T Technology Services Limited (Delhi)'),
('CYS_VA_PA1', '260166-LGB VAPT', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_PROF_SER32', '260167 - LGB Lap & Desktop Rental', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_SUP213', '260168 - Supply of UTP Lic_FortiGate FW', 'Aadit Technologies Private Limited'),
('SI_AMC117', '260173 - Extended Wty for 2 years', 'Kerala State Electricity Board Limited'),
('SI_IMP201', '260187 - Rossi Addl Work FW Ren', 'Rossi Gearmotors (India) Pvt Ltd'),
('SP_SUB_SER8', '260189-Royal Sundaram License Renewal', 'Royal Sundaram General Insurance Co. Limited'),
('SI_AMC118', '260190- AMC Renewal', 'EASTVANTAGE PRIVATE LIMITED'),
('SI_SUP214', '260191-LGB Support Services', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_SUP215', '260192- LGB Support Services', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_IMP203', '260194-TNSCHOOL_Additnal', 'KS SMART SOLUTIONS PRIVATE LIMITED'),
('SI_SUP216', '260195 - GKNM Nursing Switch supply', 'GKNM College of Nursing'),
('SI_AMC119', '260197 - Firewall Support Renewal', 'Amrita Vishwa Vidyapeetham(KL)'),
('SI_SUP217', '260198 - MAK Controls supply', 'Mak Controls and Systems Pvt Ltd'),
('MS_CLOUD11', '260199', 'International Airport Hotels and Resorts'),
('CPSO770', '260211', 'Bangalore International Airport Limited'),
('CYS_PROF_SER1', '260212 - Vitae International', 'Vitae International Accounting Services'),
('SI_SUP219', '260221_ITCOT_License', 'ITCOT Limited'),
('SI_SUP218', '260222 - Amrita, Kollam', 'Amrita Vishwa Vidyapeetham(KL)'),
('CL_SUB_RE3', '3yr Domain Renewal', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_IMP184', 'AAI- PAX Wi-Fi -260031', 'Airports Authority of India'),
('SI_AMC20', 'AAI, Chennai - PAVA system at Airport', 'Airports Authority of India'),
('MS_CLOUD8', 'AB Mobile & Terminals - AWS- 240385', 'AB Mobile And Terminals Private Limited'),
('EA_IMP5', 'Access control systems TAJ Hotel BIAL', 'Bangalore International Airport Limited'),
('SI_AMC65', 'Aditi_CBS350-24P-Support Contract renewl', 'Aditi Tech Consulting Private Limited- Gujarat'),
('SI_AMC64', 'Aditi_License renewal_Cisco C9200L', 'Aditi Tech Consulting Private Limited'),
('SI_IMP79', 'Aditi_SITC_Ruckes&IC switch install', 'Aditi Tech Consulting Private Limited- Gujarat'),
('SI_SUP35', 'AEH - Supply of Toners (1370A) - 10 Nos', 'Aravind Opticals (Pondicherry)'),
('SI_SUP79', 'AET Lab_Supply_TV_Samsung WM75A 75"_1Nos', 'AET LABORATORIES PVT LTD'),
('SI_O-M28', 'AIIMS Gorakhpur O&M', 'Larsen & Toubro Limited (Uttar Pradesh)'),
('SI_O-M10', 'Airport Authority, Chennai', 'Airports Authority of India'),
('EA_IMP4', 'Alathur Lift Irrigation Farmers Ass.', 'Alathur Lift Irrigation Farmers Association'),
('SP_IMP25', 'Allahabad_Supply&Impl_Backup SW_7Yr sup', 'Larsen & Toubro Limited (Uttar Pradesh)'),
('CPSO571', 'Alliance-DCIS wise P/L Report', 'Alliance Alliance - BU'),
('CPSO583', 'Alliance-DCIS wise P/L Report', 'Alliance Alliance - BU'),
('CPSO581', 'Alliance-DT wise P/L Report', 'Alliance Alliance - BU'),
('CPSO580', 'Alliance-E2C wise P/L Report', 'Alliance Alliance - BU'),
('CPSO582', 'Alliance-ET wise P/L Report', 'Alliance Alliance - BU'),
('MS_SUP18', 'AMC for IT', 'BILT GRAPHIC PAPER PRODUCTS LIMITED'),
('SI_O-M9', 'AMC for IT asset with Manpower at BGPPL', 'BILT GRAPHIC PAPER PRODUCTS LIMITED'),
('SI_AMC17', 'AMC for Server & Work station at BGPPL', 'BILT GRAPHIC PAPER PRODUCTS LIMITED'),
('SI_AMC8', 'AMC for switches O&M', 'DEFENCE SERVICES STAFF COLLEGE'),
('SI_AMC4', 'AMC of Core & Data Centre switches', 'Elgi Equipment Limited'),
('SI_AMC', 'AMC of Datacenter Assets', 'MAHANAGAR TELEPHONE NIGAM LIMITED'),
('SI_AMC71', 'AMC of FIrewall & Wifi AP', 'Elgi Equipment Limited'),
('FIELD_O-M9', 'AMC of IBM server and Storage', 'Siemens Energy Industrial Turbomachinery India Pvt. Ltd'),
('FIELD_O-M8', 'AMC of LIS machines', 'Mahanagar Telephone Nigam Limited-Delhi'),
('FIELD_O-M6', 'AMC of Network and compute', 'Siemens Limited (Maharashtra)'),
('FIELD_O-M4', 'AMC of Plotter', 'MNEC CONSULTANTS PRIVATE LIMITED'),
('CPSO96', 'AMC of Routers and Switches', 'THE FERTILISERS AND CHEMICALS TRAVANCORE'),
('SP_AMC1', 'AMC of Servers and Firewall (IT infra)', 'Siemens Limited (Maharashtra)'),
('SI_AMC6', 'AMC of Servers, Printers, Kiosk', 'Nuclear Power Corporation Of India Ltd.,'),
('FIELD_O-M2', 'AMC of Servers, Storage, FW, Switches', 'International Airport Hotels and Resorts'),
('SI_AMC55', 'AMC of Servers(IBM&Cisco) & Storage', 'SIEMENS ENERGY INDUSTRIAL TURBOMACHINERY INDIA PRIVATE LIMIT'),
('SP_AMC5', 'AMC of Storage', 'DRESSER RAND INDIA PVT.LTD. (Gujarat)'),
('SP_AMC4', 'AMC of Storage', 'Dresser-Rand India Pvt Ltd (Pune)'),
('FIELD_O-M3', 'AMC of Switches, AP & VMware', 'Malnad College of Engineering'),
('CL_SUB_RE4', 'AMC Renewal for Email hosting', 'Readylink Internet Services Limited'),
('MS_IMP1', 'Annual subscr with implementation', 'SS SUPPLY CHAIN SOLUTIONS PVT. LTD'),
('CL_SUP13', 'Application hosting on aws cloud', 'CLUTCH HEALTH PRIVATE LIMITED'),
('DC_SUP3', 'APSFL DC (Furniture Supply Order)', 'Larsen & Toubro Limited (Andhra Pradesh)'),
('DC_SUP8', 'APSFL DC(Civil Items Supply)', 'Larsen & Toubro Limited (Andhra Pradesh)'),
('DC_SUP9', 'APSFL DC(Electrical Materials Supply)', 'Larsen & Toubro Limited (Andhra Pradesh)'),
('DC_SUP10', 'APSFL DC(ELV Items Supply)', 'Larsen & Toubro Limited (Andhra Pradesh)'),
('DC_SUP4', 'APSFL DC(HVAC Supply Order)', 'Larsen & Toubro Limited (Andhra Pradesh)'),
('DC_IMP11', 'APSFL DC(Implementation Work Order)', 'Larsen & Toubro Limited (Andhra Pradesh)'),
('SI_SUP26', 'Aravind Eye Hospital', 'GOVEL TRUST'),
('CPSO754', 'Aruba Training - 250317', 'Microland Limited'),
('SI_IMP148', 'Ashok Leyand - 250189', 'ASHOK LEYLAND LTD.'),
('DC_CON21', 'Assessment Report for Space World DC', 'Space World Data Centre Private Limited'),
('EA_IMP8', 'Assest Management', 'SUNDARAM CLAYTON LIMITED'),
('EA_IMP7', 'Asset management at Sundaram clayton', 'SUNDARAM CLAYTON LIMITED'),
('SI_IMP28', 'Asti Electronics_Supply&Inst_Dell Server', 'ASTI ELECTORNICS INDIA PVT. LTD'),
('SI_O-M8', 'AVANTHA HOLDINGS LIMITED', 'AVANTHA HOLDINGS LIMITED'),
('CL_SUP12', 'AWS Cloud', 'SkoolcomTechnologies'),
('CL_SUP24', 'AWS Cloud & MS', 'ITM University Gwalior'),
('CL_SUP20', 'AWS Cloud billing transition', 'Samvedna Senior Care Pvt Ltd,'),
('CL_SUP18', 'AWS Cloud Consumption', 'J.M.J Educational Society'),
('CL_NEW_SUB2', 'AWS Cloud subscription services', 'Karnataka Health Promotion Trust'),
('CL_SUP15', 'AWS Consumption charges', 'ITM University Gwalior'),
('CL_SUP16', 'AWS Consumption charges', 'ITM University Gwalior'),
('CL_SUP14', 'AWS Monthly consumption charges', 'GEM Hospital And Research Center'),
('CL_SUP19', 'AWS Monthly consumption charges', 'Sri Krishna Education Trust'),
('MS_CLOUD1', 'AWS Monthly consumption charges & MS', 'K.Palaniyappa Memorial Educational Trust'),
('MS_CLOUD2', 'AWS Order- Hetero', 'Hetero Healthcare Limited'),
('CL_SUP21', 'AWS subscription &  MS', 'INVEST INDIA'),
('MS_SUP26', 'Azure Consumption', 'JAWAHARLAL NEHRU CENTRE FOR ADVANCED SCIENTIFIC RESEARCH'),
('MS_SUP11', 'Azure Consumption Charges', 'AB Mobile And Terminals Private Limited'),
('MS_SUP10', 'Azure Manage services Charges', 'SPACE WORLD GROUP LLP'),
('SI_CON12', 'Bangalore Metro Rail Corporation Phase 2', 'L&T Technology Services Limited (MH)'),
('CPSO325', 'BIAL - CWH- 230406', 'Bangalore International Airport Limited'),
('SP_SUB_SER6', 'BIAL - F5 LLB Renewal 2023 - 240370', 'Bangalore International Airport Limited'),
('SI_SUP177', 'BIAL - SVNT - Cisco Switch - 250182', 'SVNT Infotech Pvt Ltd'),
('SI_PROF_SER1', 'BIAL -T1- Advanced Services-230163', 'Bangalore International Airport Limited'),
('SI_IMP93', 'BIAL Additional Order 02 - 240123', 'Bangalore International Airport Limited'),
('SP_IMP7', 'Bial Ancillary Spare supply 210045', 'Larsen & Toubro Limited (Karnataka)'),
('SI_IMP165', 'BIAL T1 Refresh - 250306', 'Bangalore International Airport Limited'),
('SI_IMP24', 'BIAL VPN Migration', 'Bangalore International Airport Limited'),
('SI_SUP9', 'BIAL_ALPHA 3 Building', 'Bangalore International Airport Limited'),
('SI_IMP156', 'BIAL_SITC Garden Pavilion_Cisco Network', 'Bangalore International Airport Limited'),
('SP_AMC11', 'BIAL- F5 LLB Renewal - 230752', 'Bangalore International Airport Limited'),
('EA_IMP1', 'BIAL- T1- IVRS-230077', 'Bangalore International Airport Limited'),
('SP_IMP26', 'BIAL-Passenger WIFI-230603', 'Bangalore International Airport Limited'),
('SP_IMP27', 'BIAL-T1- Additional order - 230542', 'Bangalore International Airport Limited'),
('SI_PROF_SER15', 'BIOLOGICAL E LIMITED', 'BIOLOGICAL E. LIMITED'),
('SP_AMC9', 'BIOLOGICAL E.Ltd_Renewal_InsightOps/DR', 'BIOLOGICAL E. LIMITED'),
('DC_IMP30', 'BLUEPRINT PROJECTS LLP', 'BLUEPRINT PROJECTS LLP'),
('DC_CON26', 'BMS Consulting - UC3 FACTORY GUJARAT', 'Meinhardt EPCM (lndia) Private Limited'),
('DC_IMP15', 'BPCL (Smart Rack Solution - DC/DR)', 'BHARAT PETROLEUM CORPORATION LIMITED'),
('SI_SUP71', 'C2S Technologies India Pvt Ltd', 'C2S Technologies India Pvt Ltd'),
('SP_IMP32', 'Cable Masking-230770', 'Siemens Limited (Maharashtra)'),
('FIELD_O-M5', 'CAMC of Networking and', 'Indian Navy - HQSNC Naval Base Kochi'),
('SI_SUP88', 'CARE - Supply of Smart LED 32 inch TV', 'Quality Care India Limited- Orissa'),
('SI_IMP69', 'CARE_BBSR_SITC', 'Quality Care India Limited- Orissa'),
('SI_IMP71', 'CARE_CARE_SITC_Rangareddy_HYD', 'Quality care India Limited-Telangana'),
('SI_IMP66', 'CARE_Indore_SITC', 'CARE CHL HOSPITALS-INDORE'),
('SI_IMP70', 'CARE_SITC_Banjara hills_Core SW Install', 'Quality care India Limited-Telangana'),
('SI_IMP77', 'CARE_SITC_Banjara Hills_HYD', 'Quality care India Limited-Telangana'),
('SI_IMP72', 'CARE_SITC_Chaderghat_HYD', 'Quality care India Limited-Telangana'),
('SI_IMP76', 'CARE_SITC_Musheerabad', 'Quality care India Limited-Telangana'),
('SI_IMP73', 'CARE_SITC_Namplli_2_CBS 24T&48T_HYD', 'Quality care India Limited-Telangana'),
('SI_SUP87', 'CARE_Supply of LED display (QB43B)_6 Nos', 'Quality care India Limited-Telangana'),
('SI_PROF_SER9', 'CD Technotex LLP', 'CD Technotex LLP'),
('SI_SUP7', 'CEG_KSDC', 'Centre for e-Governance'),
('SI_IMP51', 'Chaitanya India - Ruckus Switches', 'CHAITANYA INDIA FIN CREDIT PVT LTD'),
('SI_IMP39', 'Chaitanya India Fin Credit pvt ltd', 'CHAITANYA INDIA FIN CREDIT PVT LTD'),
('SI_SUP152', 'Checktronix_Supply and AMC_Meraki MX250', 'Checktronix India Private Ltd'),
('SP_CON1', 'Cisco -AS-T1- Wireless Survey-230387', 'Avacend Solutions Private Limited'),
('SI_AMC69', 'Cisco Router License renewal', 'LeasePlan India Private Limited'),
('SI_SUP19', 'Cisco switch supply', 'Dr. Rela Institute & Medical Centre'),
('SP_IMP8', 'Cisco VPN License', 'KERALA UNIVERSITY OF DIGITAL SCIENCES, INNOVATION AND TECHNO'),
('CL_SUP25', 'Cloud Consumption', 'Vaishnavi Infrastructure Pvt Ltd'),
('CL_SUP17', 'CLOUD INFRA MANAGED SERVICES', 'AZISTA INDUSTRIES PVT LTD'),
('FIELD_IMP1', 'CMRL - Phase II(ASA-07)', 'CHENNAI METRO RAIL LIMITED'),
('CPSO752', 'COMPANY SECEARTY - Google Work space', 'Company Secretary In Practice CS Dwarakanath C'),
('DC_CON11', 'Concept Design of ICT Infra - Guwahati', 'Meinhardt EPCM (lndia) Private Limited'),
('DC_CON10', 'Concept Design of ICT Infra - Jaipur', 'Meinhardt EPCM (lndia) Private Limited'),
('DC_CON1', 'Concept Design of ICT Infra - Trivandrum', 'Meinhardt EPCM (lndia) Private Limited'),
('DC_CON38', 'Consultancy Services for PAL-2 Projects', 'Meinhardt EPCM (lndia) Private Limited'),
('DC_CON39', 'Consultancy Services for RailTel DC -SC', 'RailTel Corporation of India Ltd.(Hyd)'),
('DC_CON13', 'Consultancy Services for UNMS Project', 'Larsen & Toubro Limited (Delhi)'),
('DC_CON5', 'Consulting for IIT Bombay HPC-BYOH DC', 'Indian Institute of Technology Bombay'),
('DC_CON37', 'Consulting of New MS HYD-16 DC', 'Meinhardt EPCM (lndia) Private Limited'),
('DC_CON31', 'Consulting Service  for Federal Bank DC', 'The Federal bank limited Information Technology Department'),
('DC_CON36', 'Consulting service for Jaipur airport', 'RSP DESIGN CONSULTANTS (INDIA) PVT LTD'),
('DC_CON2', 'Consulting services - BACL Telecom DC', 'Meinhardt EPCM (lndia) Private Limited'),
('DC_CON18', 'Consulting Services AET laboratories', 'AET LABORATORIES PVT LTD'),
('DC_CON41', 'CONSULTING SERVICES FOR BLUE STAR-MUMBAI', 'BLUE STAR LIMITED'),
('DC_CON9', 'Consulting Services for CDAC DC Noida', 'Center for Development of Advanced Computing (Noida)'),
('DC_CON35', 'Consulting services for Microsoft HYD06', 'Meinhardt EPCM (lndia) Private Limited'),
('DC_CON27', 'Consulting Services for Villaggio Estate', 'VILLAGIO ESTATES LLP'),
('SP_IMP14', 'Contact stand - 230157', 'Bangalore International Airport Limited'),
('SI_IMP3', 'Corporate Office - WiFi', 'Elgi Equipment Limited'),
('SI_IMP27', 'CPWD IIT Palakkad - Campus Network', 'CENTRAL PUBLIC WORKS DEPARTMENT PALAKKAD'),
('DC_IMP29', 'CRIS(29 Numbers Rack Supply)', 'Centre for Railway Information Systems'),
('DC_SUP1', 'DC broken door supply', 'Larsen & Toubro Limited (Telangana)'),
('DC_CON30', 'Design of ELV and ICT for MMCH', 'Meinhardt EPCM (lndia) Private Limited'),
('DC_CON7', 'Design Services - Care Hospitals', 'QUALITY CARE HOSPITAL INDIA LTD Vizag-1'),
('SP_IMP38', 'Design SITC for Govt DC Malawi-240444', 'Netcon Technologies Private Limited'),
('CL_SUP8', 'Devi Shakuntala - Cloud Billing', 'Devi Shakuntala Thakral Charitable'),
('MS_SUP12', 'Devops - Azure', 'Azista Industries Pvt Ltd'),
('SI_IMP29', 'Dhanlaxmi_Supply and Implement of SLB', 'DHANALAKSHMI BANK'),
('SI_AMC35', 'Dhariwala Infra - professional service', 'DHARIWAL INFRASTRUCTURE LIMITED'),
('CL_SUB_RE5', 'Domain Renewal', 'SCM Garments Pvt Limited'),
('SI_AMC28', 'Dresser-Rand India Pvt Ltd', 'Dresser-Rand India Pvt Ltd (Pune)'),
('CL_SUP26', 'DY Patil - AWS- 240024', 'D. Y. Patil International University'),
('CL_SUP4', 'DY Patil International University', 'D. Y. Patil International University'),
('SI_PROF_SER8', 'E-Hosting Services (75 user with 25GB)', 'CETHAR ENERGY LIMITED'),
('DC_O-M2', 'e-Shiksha Large Field O&M', 'Larsen & Toubro Limited (Tamilnadu)'),
('DC_IMP18', 'e-Shiksha(40 Thin Client SITC)', 'Tamil Nadu State Mission of Education for All'),
('SI_SUP137', 'Eastvantage - 240516-Supply ID card', 'EASTVANTAGE PRIVATE LIMITED'),
('SI_SUP53', 'Eastvantage Private Limited', 'EASTVANTAGE PRIVATE LIMITED'),
('SI_AMC27', 'Eastvantage Private LImited', 'EASTVANTAGE PRIVATE LIMITED'),
('SI_SUP76', 'Eastvantage pvt ltd 230734', 'EASTVANTAGE PRIVATE LIMITED'),
('SI_SUP58', 'Eastvantage-Dell PowerEdge1 mnt rental', 'EASTVANTAGE PRIVATE LIMITED'),
('MS_NXAAS4', 'EDR for endpoints', 'Karnataka Power Transmission Corp ltd'),
('SI_AMC10', 'Elgi ACP AMC', 'Elgi Equipment Limited'),
('SI_AMC23', 'Elgi BLR & Foundry', 'Elgi Equipment Limited'),
('SI_O-M3', 'Elgi FMS order', 'Elgi Equipment Limited'),
('SI_O-M1', 'Elgi FMS Service', 'Elgi Equipment Limited'),
('SI_AMC21', 'Elgi HO AMC', 'Elgi Equipment Limited'),
('CPSO577', 'Enterprise - DT wise P/L report', 'Enterprise Enterprise - BU'),
('CPSO576', 'Enterprise - E2C wise P/L report', 'Enterprise Enterprise - BU'),
('CPSO579', 'Enterprise-DCIS wise P/L report', 'Enterprise Enterprise - BU'),
('CPSO578', 'Enterprise-ET wise P/L report', 'Enterprise Enterprise - BU'),
('DC_SUP11', 'Extinguisher Refilling', 'Larsen & Toubro Limited (Telangana)'),
('CPSO22', 'EZ Vidya - O365', 'EZ Vidya Pvt Ltd'),
('CL_SUP6', 'EZ Vidya Pvt Ltd', 'EZ Vidya Pvt Ltd'),
('MS_SUP1', 'EZ Vidya Pvt Ltd -O365 & Online Archieve', 'EZ Vidya Pvt Ltd'),
('CL_SUP7', 'EZ Vidya Pvt Ltd-UBX', 'EZ Vidya Pvt Ltd'),
('CL_SUP3', 'EZ Vidya- AWS', 'EZ Vidya Pvt Ltd'),
('SP_SUB_SER5', 'F5 Server Subs renewal', 'Royal Sundaram General Insurance Co. Limited'),
('MS_SUP20', 'Fiber 150 Mbps ILL for 3 years', 'Infonet Comm Enterprises Pvt Ltd'),
('SI_IMP192', 'Fortigate-2200E AMC 1 year Renewal', 'Bangalore International Airport Limited'),
('SI_AMC7', 'Fortinet Firewall Renewal', 'TAMILNADU PUBLIC SERVICE COMMISSION'),
('SI_SUP23', 'Fortinet Firewall supply', 'Kongunadu Infra Developers'),
('SI_IMP4', 'Fortinet Firewall upgrade', 'GKM Global Services Private Limited'),
('SP_SUB_SER2', 'Fortinet License Renewal', 'PAANINI, INC'),
('SI_SUP95', 'FUSO - VMWARE VSphere8 ESSEN KIT- 3Yrs', 'FUSO GLASS INDIA PVT LTD'),
('SI_PROF_SER23', 'FY25- 250418', 'DIGITAL IT INFRA PRIVATE LIMITED'),
('MS_SUP31', 'GAJAANANDA JEWELLERY MAART INDIA PVT LTD', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SUP32', 'Gajaananda Jewellery Mart India P Ltd', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SUP33', 'Gajaananda Jewellery Mart India P Ltd', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SUP34', 'Gajaananda Jewellery Mart India P Ltd', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SUP35', 'Gajaananda Jewellery Mart India P Ltd', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SUP36', 'Gajaananda Jewellery Mart India P Ltd', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SUP37', 'Gajaananda Jewellery Mart India P Ltd', 'Gajaananda Jewellery Mart India P Ltd'),
('CPSO685', 'Gajaananda Jewellery Mart India P Ltd', 'Gajaananda Jewellery Mart India P Ltd'),
('MS_SUP38', 'Gajaananda Jewellery Mart India P Ltd', 'GAJAANANDA JEWELLERY MAART INDIA PVT LTD'),
('SI_SUP190', 'GE Supply', 'GE Renewable Energy Technologies Pvt Ltd'),
('SI_SUP41', 'GKM Global HDD', 'GKM Global Services Private Limited'),
('SI_IMP32', 'GKNM WiFi & Switch supply & Installation', 'G.Kuppuswamy Naidu Memorial Hospital'),
('DC_SUP12', 'Goa  MS Chequered Plate', 'Larsen & Toubro Limited (Goa)'),
('DC_IMP7', 'Goa FSS', 'LARSEN & TOUBRO LIMITED(Bainguinim)'),
('CPSO183', 'Godrej & Boyce Mfg. Co. Ltd-230004', 'GODREJ AND BOYCE MFG CO LTD'),
('CL_SUP9', 'Gyan Ganga Group of Institutions', 'Gyan Ganga Group of Institutions'),
('CPSO366', 'Hardware and Software Support', 'National Remote Sensing Centre Indian Space Research Organiz'),
('DC_CON20', 'HCS Network Consulting & ITMS Project', 'Larsen & Toubro Limited (Telangana)'),
('DC_CON16', 'HCS TPHQ Consulting Project', 'Larsen & Toubro Limited (Telangana)'),
('SP_IMP23', 'HCS_VMware_Insttall,Test&Commisiong', 'Larsen & Toubro Limited (Telangana)'),
('SI_IMP7', 'HDD replacement @ GKM', 'GKM Global Services Private Limited'),
('CL_NEW_SUB1', 'HHCL Azure Services', 'Hetero Healthcare Limited'),
('SI_AMC54', 'HP Aruba WLC AMC', 'Siemens Limited (Maharashtra)'),
('CL_SUP28', 'IAHR M365 - 250093', 'International Airport Hotels and Resorts'),
('DC_CON28', 'ICT & ELV design for Multi-mode Cargo', 'Meinhardt EPCM (lndia) Private Limited'),
('DC_CON15', 'ICT & Security Services at Ahmedabad', 'RSP DESIGN CONSULTANTS (INDIA) PVT LTD'),
('DC_CON24', 'ICT Consulting for 3 Airports', 'Meinhardt EPCM (lndia) Private Limited'),
('SI_IMP157', 'IICC_NEW SUPPLY', 'Larsen & Toubro Limited (Delhi)'),
('SP_SUP5', 'IICC-230849', 'Larsen & Toubro Limited (Tamilnadu)'),
('MS_SEC1', 'IIM-B -ISO Audit', 'INDIAN INSTITUTE OF MANAGEMENT BANGALORE'),
('CPSO8', 'IIM-B-ISOAudit', 'INDIAN INSTITUTE OF MANAGEMENT BANGALORE'),
('CL_SUP2', 'IIM-K-AWS Consumption', 'Indian Institute of Management (Kozhikode)'),
('CPSO153', 'IISC -Bangalore-210146', 'Center for Brain Research'),
('SI_IMP68', 'IIT - Thirupati - SITC', 'INDIAN INSTITUTE OF TECHNOLOGY TIRUPATI'),
('SI_AMC22', 'IIT Palakkad - CCTV AMC', 'Indian Institute of Technology Palakkad'),
('SI_IMP91', 'IIT-Madras 240097', 'IITM Pravartak Technologies Foundation'),
('SI_SUP83', 'IIT-Supply Switches and Cables Bombay', 'Indian Institute of Technology Bombay'),
('SI_PROF_SER31', 'IITM Reaserach_Senior Network Engineer', 'IITM Research Park'),
('SI_IMP80', 'Imp,Testing & comissioning-230900', '7H Business Solutions Private Limited'),
('MS_INFRA1', 'Indian Institute of Management (IIM-T)', 'Indian Institute of Management Tiruchirappalli'),
('SI_IMP5', 'Infonet Comm_Router & L2 switch delivery', 'Infonet Comm Enterprises Pvt Ltd'),
('SI_IMP64', 'Infonet DC Migration', 'Infonet Comm Enterprises Pvt Ltd'),
('DC_AMC6', 'INS Garuda(CAMC Smart Rack 03 - Vertiv)', 'Indian Navy - HQSNC Naval Base Kochi'),
('DC_IMP4', 'Interior work at DSS - PT&D', 'Larsen & Toubro Limited (Tamilnadu)'),
('SP_IMP50', 'IOCL - Firewall Migration - 250374', 'Indian Oil Corporation Limited'),
('SI_SUP5', 'ISB Mohali', 'Indian School of Business'),
('DC_CON19', 'IT Infrastructure Consulting Services', 'Larsen & Toubro Limited (Telangana)'),
('SI_AMC103', 'ITCOT-Firewall Licence Renewal-250368', 'ITCOT Limited'),
('DC_IMP33', 'ITI DC & SNOC Implemention', 'ITI Limited'),
('SP_SUB_SER7', 'Jhansi EMS 4th Renewal - 250101', 'L&T TECHNOLOGY SERVICES LIMITED - Uttar Pradesh'),
('DC_IMP19', 'JHANSI SMART CITY - 230925', 'Larsen & Toubro Limited (Uttar Pradesh)'),
('DC_IMP28', 'Jhansi Smart City(LCP Compressor - SITC)', 'L&T TECHNOLOGY SERVICES LIMITED - Uttar Pradesh'),
('SI_IMP14', 'Karnataka Forest Department-220230', 'Karnataka Forest Department'),
('SI_IMP38', 'KFD-230546', 'Karnataka Forest Department'),
('SI_AMC11', 'KKNPP Cisco & Checkpoint renewal', 'Nuclear Power Corporation Of India Ltd.,'),
('MS_SEC2', 'KPTCL Firewall Renewal and Support AMC', 'Karnataka Power Transmission Corp ltd'),
('DC_O-M4', 'KSEB FMS 2 Months(Jul 22 - Aug 22)', 'Kerala State Electricity Board Limited'),
('DC_O-M3', 'KSEB FMS 3 Months(Mar 22 - Jun 22)', 'Kerala State Electricity Board Limited'),
('DC_O-M5', 'KSEB FMS 3 Months(Sep 22 - Nov 22)', 'Kerala State Electricity Board Limited'),
('SI_SUP25', 'Kumaran Firewall supply', 'KUMARAN GIN AND PRESSING PRIVATE LIMITED'),
('SI_SUP44', 'L and T Delhi - 210175', 'Larsen & Toubro Limited (Delhi)'),
('SP_IMP28', 'L&T - Active Components - T-Fiber', 'Larsen & Toubro Limited (Telangana)'),
('CPSO163', 'L&T - INA Vizag -230177', 'Larsen & Toubro Limited (Andhra Pradesh)'),
('SI_SUP123', 'L&T - NIC cloud datacenter Red hat', 'Larsen & Toubro Limited (Odisha)'),
('SP_SUP4', 'L&T - Supply of LR (Module_2 Nos)_SOC_HQ', 'Larsen & Toubro Limited (Tamilnadu)'),
('SI_CON8', 'L&T - T-Fiber - Supply of Manpower', 'Larsen & Toubro Limited (Telangana)'),
('SP_SUP3', 'L&T - T2 Additional Switch - 230730', 'Larsen & Toubro Limited (Karnataka)'),
('SP_IMP16', 'L&T Additional supply 230281-230005', 'Larsen & Toubro Limited (Karnataka)'),
('SI_AMC2', 'L&T AIIMS AMC', 'Larsen & Toubro Limited (Uttar Pradesh)'),
('SI_IMP133', 'L&T BSNL Cloudera - 240670', 'L&T Technology Services Limited (Delhi)'),
('DC_IMP13', 'L&T HQ(DSS Baffle Ceiling SI)', 'Larsen & Toubro Limited (Tamilnadu)'),
('SP_AMC8', 'L&T_AMC of Fortinets Firewall SW License', 'Larsen & Toubro Limited (Maharashtra)'),
('SP_IMP37', 'L&T_Server&Storage_Chennai campus', 'Larsen & Toubro Limited (Tamilnadu)'),
('SP_SUP2', 'L&T_Supply of Aruba Switches_Faridabad', 'Larsen & Toubro Limited (Haryana) - Realty Division'),
('SI_SUP49', 'L&T_Supply_100F_Cyber Defence Center_HQ', 'Larsen & Toubro Limited (Tamilnadu)'),
('SP_SUP1', 'L&T_Supply_FG 100 F_Global NOC_HQ', 'Larsen & Toubro Limited (Tamilnadu)'),
('SP_SUP6', 'L&T_Supply_SR & LR Modules_2Nos_HQ_NOC', 'Larsen & Toubro Limited (Tamilnadu)'),
('SP_IMP31', 'L&T- Deployment_ICT works', 'Larsen & Toubro Limited (Delhi)'),
('SI_SUP2', 'L&T- T2- Additional AP Order- 230083', 'Larsen & Toubro Limited (Karnataka)'),
('SP_IMP13', 'L&T-T2- Design & Implementation- 230386', 'Larsen & Toubro Limited (Karnataka)'),
('SI_CON9', 'L2 Resource - Network Security-240135', 'Siemens Technology and Services Pvt Ltd.'),
('SI_SUP13', 'Larsen & Toubro , Manapakkam', 'Larsen & Toubro Limited (Bihar)'),
('SP_AMC7', 'Larsen & Toubro , Manapakkam-230009', 'Larsen & Toubro Limited (Maharashtra)'),
('SI_AMC16', 'LCC Firewall Renewal', 'Lakshmi Card Clothing Mfg Company'),
('SI_IMP43', 'LeasePlan_UCS Server & Flex License', 'LeasePlan India Private Limited'),
('SI_SUP186', 'LGB - Corporate Office Aruba Wifi', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_SUP183', 'LGB - Pongalur Aruba Wifi', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_IMP159', 'LGB - Pongalur Turnstyle', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_SUP187', 'LGB- Corp. Office Forti-Analyzer Supply', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_IMP120', 'LGB-SITC of Active & Passive Components', 'L.G.BALAKRISHNAN & BROS LIMITED NAGPUR PLANT - ICD'),
('SP_IMP29', 'LIAL- MTCS -230427', 'Lucknow International Airport Ltd'),
('SP_IMP4', 'LTI - FIU', 'Larsen & Toubro Infotech Limited (Delhi)'),
('SI_CON4', 'LTIMindtree Limited-230765', 'LTIMindtree Limited'),
('CL_SUB_RE1', 'MAILNGX - CLOUD ZIMBRA BASIC SUITE -LCC', 'Lakshmi Card Clothing Mfg Company'),
('SI_IMP123', 'Manipal - Cisco Meraki - IMP - 240394', 'MANIPAL HOSPITALS PRIVATE LIMITED'),
('SI_IMP122', 'Manipal - Cisco Miraki - IMP- 240403', 'Manipal Health Enterprises Pvt. Ltd.'),
('SI_IMP128', 'Manipal - Radware -240605', 'Manipal Health Enterprises Pvt. Ltd.'),
('SP_IMP45', 'Manipal - Wireless Imp - 240437', 'MANIPAL HOSPITALS PRIVATE LIMITED'),
('SI_AMC44', 'Manipal Health Enterprise-230838', 'Manipal Health Enterprises Pvt. Ltd.'),
('SP_IMP40', 'Manipal Meraki AP - 240198', 'Manipal Health Enterprises Pvt. Ltd.'),
('SP_IMP39', 'Manipal Meraki AP - 240199', 'Manipal Health Enterprises Pvt. Ltd.'),
('SI_PROF_SER11', 'Manipal Trelix- 240422', 'Manipal Health Enterprises Pvt. Ltd.'),
('CPSO564', 'Manipal Trellix Renewal - 240216', 'Manipal Health Enterprises Pvt. Ltd.'),
('CYS_IMP1', 'Manipal Umbrella - 240074', 'Manipal Health Enterprises Pvt. Ltd.'),
('SI_IMP108', 'Manipal-240363', 'MANIPAL HOSPITALS PRIVATE LIMITED'),
('SI_IMP62', 'Manipal-SITC of meraki AP and router', 'Manipal Health Enterprises Pvt. Ltd.'),
('SI_SUP122', 'ManipalMeraki-240402', 'Manipal Health Enterprises Pvt. Ltd.'),
('CPSO128', 'MAPAL - Active Network components', 'MAPAL India Private Limited'),
('SI_IMP26', 'MAPAL - Passive Implementation', 'MAPAL India Private Limited'),
('SI_SUP24', 'Matrimony - Qnap supply', 'Matrimony.com Limited'),
('DC_O-M7', 'MCS Non-IT Services', 'Larsen & Toubro Limited (Maharashtra)'),
('SI_O-M6', 'MCS O & M', 'Larsen & Toubro Limited (Maharashtra)'),
('SI_O-M21', 'MCS O&M for 7 months', 'Larsen & Toubro Limited (Maharashtra)'),
('SI_O-M26', 'MCS Order for 5 months', 'Larsen & Toubro Limited (Maharashtra)'),
('MS_SEC4', 'MDR- Basic Kaspersky', 'Fyers Securities Private Limited'),
('SI_IMP78', 'Medi Assist Healthcare-240002', 'Medi Assist Healthcare service Limited'),
('SI_AMC34', 'Medversity-License Renewal SONICWALL_1Yr', 'Medvarsity Online Limited'),
('SI_PROF_SER5', 'Meraki Firewall support Charges', 'NRD TECH PRIVATE LIMITED'),
('SI_IMP22', 'MG University CCTV/VOIP/ACS', 'MGU INNOVATION FOUNDATION'),
('SI_SUP167', 'MHE_Supply of Meraki and Lic_Jayanagar', 'Manipal Health Enterprises Pvt Ltd.'),
('SI_IMP127', 'MIAL - IVRS - 240584', 'MUMBAI INTNL AIRPORT LTD'),
('SP_IMP24', 'MIAL- IVRS-230211', 'ADANI ENTERPRISES LTD'),
('MS_SUP13', 'Microsoft 365 Business Basic Licenses', 'EZ Vidya Pvt Ltd'),
('MS_SUP14', 'Microsoft O3065 Monthly Support', 'SPACE WORLD GROUP LLP'),
('MS_SUP27', 'Microsoft O365 - 230936', 'EZ Vidya Pvt Ltd'),
('MS_SUP4', 'Microsoft O365 Requirement', 'SPACE WORLD GROUP LLP'),
('MS_SUP19', 'Microsoft Virtual machine', 'SPACE WORLD GROUP LLP'),
('SI_IMP95', 'Mindsprint-240127', 'Mindsprint Digital India PvtLtd'),
('CL_SUP22', 'Moodle migration to AWS Cloud & MS', 'INTEGRAL EDUCATION SOCIETY'),
('DC_CON29', 'MS DC HYD16 Consulting Services', 'Meinhardt EPCM (lndia) Private Limited'),
('SI_SUP18', 'Musigma', 'Mu Sigma Business Solutions Pvt. Ltd.'),
('SI_AMC77', 'Musigma_HPE Aruba Central AP 3-yr subscr', 'Mu Sigma Business Solutions Pvt. Ltd.'),
('SI_IMP63', 'Musigma_Imple&Migration_Aruba Swiches&AP', 'Mu Sigma Business Solutions Pvt. Ltd.'),
('SI_IMP33', 'N Assets WiFi & Firewall', 'N ASSET SERVICES'),
('SP_IMP47', 'NCA-240661', 'Larsen & Toubro Limited, Construction'),
('DC_CON17', 'Network Consultant for IIM Ahmedabad', 'Indian Institute of Management Ahmedabad'),
('MS_SEC5', 'NFSU - 240007', 'National Forensic Sciences University'),
('SI_SUP86', 'NIMS Hospital- 24Port Switch 230905', 'Wipro GE Healthcare Private Limited'),
('SI_AMC13', 'NMDC - Network AMC & FMS', 'NMDC Ltd (Telangana)'),
('SI_IMP12', 'NMDC Limited-190183', 'NMDC Limited'),
('SI_AMC18', 'NMDC_AMC_Billing (01/06-30/11_2021)', 'NMDC Ltd (Telangana)'),
('SP_SUP7', 'Noida International Airport.-230942', 'Yamuna International Airport Pvt Ltd'),
('CL_SUP10', 'NorthTree AV & Email Security', 'SPACE WORLD GROUP LLP'),
('CL_NEW_SUB3', 'Northtree O365 & Windows Subscription', 'SPACE WORLD GROUP LLP'),
('SI_SUP16', 'Northtree Teleconsulting Llp', 'SPACE WORLD GROUP LLP'),
('SI_SUP15', 'Northtree Teleconsulting Llp', 'SPACE WORLD GROUP LLP'),
('SI_IMP2', 'Northtree Teleconsulting Llp', 'SPACE WORLD GROUP LLP'),
('SI_SUP14', 'Northtree Teleconsulting Llp', 'SPACE WORLD GROUP LLP'),
('MS_NXAAS1', 'NovaTechset Fortinet Firewall NAXAS', 'NOVA TECHSET LIMITED (Chennai)'),
('MS_NXAAS2', 'NovatechSet IaaS- Fortinet Firewall', 'NOVA TECHSET LIMITED (Bangalore)'),
('MS_SUP3', 'O365 Additional Qty Requirement', 'EZ Vidya Pvt Ltd'),
('MS_SUP7', 'O365 Business Standard', 'EZ Vidya Pvt Ltd'),
('MS_SUP8', 'O365 E1 Monthly', 'ENTERPRISEMINDS INDIA PRIVATE LIMITED'),
('CPSO100', 'On Site Warranty Support for IT Infra', 'Cochin International Airport Limited'),
('SI_O-M20', 'On-Site ARC Support for IT Services', 'PETRONET LNG LIMITED'),
('SI_PROF_SER2', 'One time FMS Service charges', 'Aviserv Airport Services Pvt Ltd'),
('SI_IMP110', 'One time imp and commission', 'Larsen & Toubro Limited (Haryana)'),
('SI_PROF_SER3', 'One time support for Firewall and WLC', 'International Airport Hotels and Resorts'),
('CL_SUP23', 'OneDrive for business', 'EZ Vidya Pvt Ltd'),
('MS_SUP30', 'OneDrive for business (Plan 2) - 240161', 'EZ Vidya Pvt Ltd'),
('MS_SUP40', 'Palo Alto Renewal', 'Mouser Electronics India Pvt Ltd'),
('SI_SUP72', 'Paradigm_Supply of SD-RED 60 Rev.1 Appli', 'ParadigmIT Technology Services Pvt Ltd'),
('SI_IMP15', 'Passive Supply and installation', 'LBS Institute of Technology for Women'),
('SI_IMP145', 'PAX - AeroPass - 250107', 'Bangalore International Airport Limited'),
('DC_IMP3', 'Petronet_DC Build', 'PETRONET LNG LIMITED'),
('DC_CON32', 'PGTL POWERTEL DC Bangalore', 'POWERGRID TELESERVICES LIMITED POWERTEL'),
('DC_IMP25', 'Pricol(Access Floor,ELV,UPS,Smart Rack)', 'PRICOL HOLDINGS LIMITED'),
('DC_SUP13', 'Pricol(FM200 Gas Refilling)', 'Pricol Limited'),
('CPSO587', 'PSU-DCIS Wise P/L report', 'Public Sector Unit-BU'),
('CPSO585', 'PSU-DT Wise P/L report', 'Public Sector Unit-BU'),
('CPSO584', 'PSU-E2C Wise P/L report', 'Public Sector Unit-BU'),
('CPSO586', 'PSU-ET Wise P/L report', 'Public Sector Unit-BU'),
('SI_SUP20', 'Rack Supply', 'PSG INSTITUTE OF MEDICAL SCI & RES'),
('MS_SUP17', 'Radware -Software subscription', 'Manipal Health Enterprises Pvt. Ltd.'),
('SI_SUP12', 'RANEXT TECHNOLOGIES PRIVATE LIMITED', 'RANEXT TECHNOLOGIES PRIVATE LIMITED'),
('SI_IMP30', 'Ranger - Passive work', 'Ranger Cotton Mills (India) Pvt Ltd'),
('SI_AMC19', 'Ranger Fortinet Renewal', 'Ranger Cotton Mills (India) Pvt Ltd'),
('SP_IMP15', 'RCP- 230158', 'Bangalore International Airport Limited'),
('DC_AMC1', 'Regional Cancer Center UPS AMC', 'Regional Cancer Centre'),
('SP_IMP6', 'Relocation of Server -gur to blr', 'Siemens Technology and Services Pvt Ltd.'),
('SP_SUB_SER4', 'Renewal of Checkpoint Firewall', 'Nuclear Power Corporation Of India Ltd.,'),
('SP_SUB_SER1', 'Renewal of Licenses', 'International Airport Hotels and Resorts'),
('SI_AMC15', 'Renewal of Meraki Devices-230137', 'Mu Sigma Business Solutions Pvt. Ltd.'),
('SI_PROF_SER6', 'Renewal of Web services', 'Gajaananda Jewellery Mart India P Ltd'),
('SI_PROF_SER24', 'RF Survey - 250416', 'V Link Systems (P) Ltd'),
('SI_IMP6', 'Rossi Gear Passive Active & VC', 'Rossi Gearmotors (India) Pvt Ltd'),
('CPSO588', 'Ruckus Renewal Chaitayan - 240283', 'CHAITANYA INDIA FIN CREDIT PVT LTD'),
('SI_SUP70', 'Samhitha Crop Care Clincs India Pvt Ltd', 'Samhitha Crop Care Clincs India Private Ltd'),
('DC_IMP22', 'SBA Info Smart Rack (End Client:IITM)', 'SBA INFO SOLUTIONS PRIVATE LIMITED'),
('DC_AMC4', 'SCTIMST(DC AMC)', 'SREE CHITRA TIRUNAL INSTITUTE FOR MEDICAL SCIENCES & TECHNOL'),
('SI_AMC9', 'Server Consolidation & Data Center', 'INTERNATIONAL ADVANCED RESEARCH CENTRE FOR POWDER METALLURGY'),
('SP_PROF_SER2', 'Server Rental Charges', 'ESAF SMALL FINANCE BANK'),
('CPSO85', 'SI of Artificial Intelligence Lab', 'Mahatma Gandhi University'),
('SI_IMP9', 'SI of SDN switches', 'KERALA UNIVERSITY OF DIGITAL SCIENCES, INNOVATION AND TECHNO'),
('SI_AMC67', 'SI_AMC- Elgi network', 'Elgi Equipment Limited'),
('SI_SUP197', 'SI- Supply - 250448', 'V Link Systems (P) Ltd'),
('SI_SUP195', 'SI- Supply - 250449', 'DIGITAL IT INFRA PRIVATE LIMITED'),
('SI_SUP105', 'Siemens - HPE Lights-Out License -240152', 'Siemens Technology and Services Pvt Ltd'),
('CPSO551', 'Siemens - HPE Smart Array-240098', 'Siemens Technology and Services Pvt Ltd'),
('CPSO758', 'Siemens - Movement - 250372', 'Siemens Healthcare Private Limited'),
('SI_IMP41', 'Siemens - Pune Aker N/w implementation', 'Siemens Technology and Services Pvt Ltd'),
('SP_IMP44', 'Siemens - Wireless imp - 240424', 'Siemens Limited (Maharashtra)'),
('SP_IMP43', 'Siemens - Wireless imp - 240426', 'Siemens Technology and Services Pvt Ltd.'),
('SI_SUP207', 'Siemens -260103 - BLR to MAA', 'Siemens Technology and Services Pvt Ltd.'),
('SI_SUP208', 'Siemens -260104- BLR to Pune', 'Siemens Technology and Services Pvt Ltd.'),
('SI_IMP191', 'Siemens -260105- SITC of Server', 'Siemens Technology and Services Pvt Ltd'),
('SP_AMC3', 'Siemens Healthcare Private Limited', 'Siemens Healthcare Private Limited'),
('SI_AMC24', 'Siemens Healthcare Pvt ltd -230516', 'Siemens Healthcare Private Limited'),
('DC_CON22', 'Siemens Kalwa Data Center', 'Siemens Limited (Maharashtra)'),
('SP_IMP20', 'Siemens Technology and service Pvt ltd', 'Siemens Technology and Services Pvt Ltd'),
('SP_IMP19', 'Siemens Technology and Service pvt ltd', 'Siemens Technology and Services Pvt Ltd.'),
('SI_SUP43', 'Siemens Technology and Services Pvt Ltd', 'Siemens Technology and Services Pvt Ltd'),
('SP_IMP18', 'Siemens Technology and Services Pvt Ltd', 'Siemens Technology and Services Pvt Ltd'),
('SI_AMC32', 'Siemens- ADV Aruba AMC renewal', 'Siemens Technology and Services Pvt Ltd.'),
('SI_IMP46', 'Siemens- Amer apex 230689', 'Siemens Technology and Services Pvt Ltd'),
('SI_CON10', 'Siemens- L2 Resource N/W Sec-250013', 'Siemens Technology and Services Pvt Ltd.'),
('SI_IMP139', 'Siemens- RF1- Advanta - 240684', 'Siemens Technology and Services Pvt Ltd.'),
('SI_IMP104', 'SII of EndPoint DMS', 'DEPARTMENT OF TREASURIES - Kerala'),
('SI_IMP111', 'SITC - IP Telephone with 2 SIP Lines', 'Networks'),
('SI_IMP138', 'SITC - Wipro GE - Active&passive Comp', 'Wipro GE Healthcare Private Limited'),
('CPSO108', 'SITC of Camera Speakers with LAN cabling', 'KERALA UNIVERSITY OF FISHERIES & OCEAN STUDIES'),
('SI_IMP97', 'SITC of cisco switch-240150', 'Malnad College of Engineering'),
('SI_IMP57', 'SITC of IT, Non IT Infra with Cloud DR', 'REConnect Energy Solutions Ltd.'),
('SP_IMP35', 'SITC of Network Switches', 'KERALA UNIVERSITY OF DIGITAL SCIENCES, INNOVATION AND TECHNO'),
('SI_IMP202', 'SITC of PA FW & User Authenticate(MFA)', 'L.G. BALAKRISHNAN & BROS LIMITED'),
('SI_IMP59', 'SITC_CARE Hospital_Vizag', 'QUALITY CARE INDIA LIMITED'),
('DC_CON23', 'Site Assessment for Federal Bank DC', 'The Federal bank limited Information Technology Department'),
('EA_PROF_SER1', 'SIte Survey charges towards', 'Wipro GE Healthcare Private Limited'),
('MS_SUP24', 'SkuTitle -Power BI Pro_Annual', 'EZ Vidya Pvt Ltd'),
('MS_SUP5', 'SOC services for BIO E', 'BIOLOGICAL E. LIMITED'),
('SI_SUP198', 'SonaComstar - Passive & SFP - 260012', 'Sona Comstar'),
('SI_IMP181', 'SonaComstar - SITC - 260002', 'Sona Comstar'),
('SI_AMC5', 'Sonicwall Renewal', 'K.Palaniyappa Memorial Educational Trust'),
('DC_CON25', 'SPCPL - ELV Consulting Services', 'SHAPOORJI PALLONJI AND COMPANY PVT LTD'),
('SI_SUP65', 'Sphoorthy_Supply of R650 AP & CiscoSG350', 'SPHOORTHY ENGINEERING COLLEGE Society Thoma Educational'),
('SI_SUP74', 'Spoorthy_Supply of 42U Rack & Sophos', 'SPHOORTHY ENGINEERING COLLEGE Society Thoma Educational'),
('MS_SEC7', 'SPOT MDR - 240076', 'International Airport Hotels and Resorts'),
('CL_SUP1', 'Sri Krishna Education Trust', 'Sri Krishna Education Trust'),
('SI_SUP78', 'STAR_48P Console System & Licenses', 'STAR India Pvt. Ltd'),
('SI_SUP94', 'Steril - CBY Appliance & Backup Exec Lic', 'STERIL-GENE LIFE SCIENCES (P) LTD'),
('DC_IMP23', 'SukhdevRaj(IIT-P, Scada System for BMS)', 'Sukhdev Raj Sharma Engineers & Contractors Pvt Ltd'),
('SI_SUP102', 'Supply & Ins. of CCTV - Care, Banjara', 'Quality care India Limited-Telangana'),
('SI_SUP101', 'Supply & install-240038', 'Manipal Health Enterprises Pvt. Ltd.'),
('CPSO553', 'Supply & SITC Juniper switches_CCTV req', 'Larsen & Toubro Limited (Tamilnadu)'),
('CPSO598', 'Supply Aditi cloudpath-240296', 'Aditi Tech Consulting Private Limited- Gujarat'),
('SI_SUP39', 'Supply of (server room sensor - 3 Nos)', 'Mane India Private Limited (Gujarat)'),
('SI_SUP106', 'Supply of CBS350-24T (1 Nos) & Implement', 'Wipro GE Healthcare Private Limited'),
('SI_SUP191', 'Supply of cisco SFP Module - MAK', 'Mak Controls and Systems Pvt Ltd'),
('SI_SUP56', 'Supply of Cisco switch_CBS350_24P NonPoE', 'Medvarsity Online Limited'),
('SI_SUP148', 'Supply of cisco-240595', 'Manipal Hospitals Private Limited'),
('SI_SUP54', 'Supply of HP laptop (2) & Desktop (2)', 'SANNITHA EDUCATIONAL INSTITUTIONS PRIVATE LIMITED'),
('SI_SUP50', 'Supply of HP Laserjet M 208DW Printer', 'GOVEL TRUST Aravind Eye Hospitals,'),
('SI_SUP37', 'Supply of HP printer ((208)-1Nos', 'GOVEL TRUST Aravind Eye Hospitals,'),
('SI_SUP38', 'Supply of HP printer (202 dw)', 'GOVEL TRUST Aravind Eye Hospitals,'),
('SI_SUP192', 'Supply of IOT switch - 250395', 'Sona Comstar'),
('SI_SUP21', 'Supply of laserjet Printer', 'GOVEL TRUST Aravind Eye Hospitals,'),
('SI_SUP46', 'Supply of license_UTP_Ahmed_Safe City', 'Larsen & Toubro Limited (Gujarat)'),
('SI_SUP84', 'Supply of meraki AP and Router-230911', 'Manipal Health Enterprises Pvt. Ltd.'),
('SI_SUP30', 'Supply of microfocus EMS-210140', 'Larsen & Toubro Limited (Uttar Pradesh)'),
('SI_SUP119', 'Supply of N/W FW (Palo Alto_440)', 'GKB VISION PRIVATE LIMITED - GOA'),
('MS_SEC9', 'Supply of Netcon-MDR', 'Netcon Technologies LLC'),
('SI_IMP116', 'Supply of Network Rack -240435', 'EASTVANTAGE PRIVATE LIMITED'),
('SI_O-M2', 'Supply of Rental Servers', 'ESAF SMALL FINANCE BANK'),
('SI_O-M16', 'Supply of Rental Switches', 'KERALA UNIVERSITY OF DIGITAL SCIENCES, INNOVATION AND TECHNO'),
('SI_SUP92', 'Supply of ruckus hardware-switch-230932', 'CHAITANYA INDIA FIN CREDIT PVT LTD'),
('EA_IMP3', 'supply of server for SIPCOT WMP', 'YAVAR TECH WORKS PRIVATE LIMITED'),
('SI_SUP89', 'Supply of Sophos FW_36 Nos', 'Samhitha Crop Care Clincs India Private Ltd'),
('SI_SUP51', 'Supply_Firewall (80F) & APs (231-3nos)', 'SPACE TELELINK LIMITED'),
('SI_SUP45', 'Supply_Fortinet Firewall_Ahmad Safe City', 'Larsen & Toubro Limited (Gujarat)'),
('SI_SUP115', 'Supply_OneDrive_business (Plan 2) subscr', 'EZ Vidya Pvt Ltd'),
('SI_SUP114', 'Supply_QNAP_Ganga CARE Hospital_Nagpur', 'GANGA CARE HOSPITAL LIMITED'),
('SI_SUP116', 'Supply_Sapphire IMS Ent Platform&Support', 'COROMANDEL INTERNATIONAL LIMITED'),
('SI_SUP118', 'Supply_Software Licenses (VPN Solution)', 'Larsen & Toubro Limited (Andhra Pradesh)'),
('SI_SUP31', 'Supply,Warranty HP Servers-190107', 'Larsen & Toubro Limited (Uttar Pradesh)'),
('SI_SUP100', 'SupplySFP module,Fc,PatchCord-240036', 'CHAITANYA INDIA FIN CREDIT PVT LTD'),
('SI_IMP11', 'Switch supply', 'KERALA UNIVERSITY OF DIGITAL SCIENCES, INNOVATION AND TECHNO'),
('SI_AMC3', 'T-Fiber AMC', 'Larsen & Toubro Limited (Telangana)'),
('SI_AMC76', 'T-Fiber Cisco Firewall license', 'Larsen & Toubro Limited (Telangana)'),
('DC_AMC8', 'T-FIBER DC Passive Infra AMC', 'Larsen & Toubro Limited (Telangana)'),
('DC_IMP21', 'T-Fiber GP Implementation, STL', 'NEXN COMMUNICATIONS PRIVATE LIMITED'),
('SP_PROF_SER3', 'T1 - WSM Project', 'Bangalore International Airport Limited'),
('SP_PROF_SER4', 'T1-AS- Additional-230924', 'Avacend Solutions Private Limited'),
('SP_IMP21', 'T2-Addon', 'Bangalore International Airport Limited'),
('SP_IMP49', 'TANFINET - SITC - 250184', 'Railtel Corporation of India Ltd.'),
('SI_SUP52', 'TANFINET - Supply_Redhat_SW & License', 'Larsen & Toubro Limited (Tamilnadu)'),
('DC_IMP5', 'TANFINET Block & GP implementation', 'Larsen & Toubro Limited (Tamilnadu)'),
('SI_IMP155', 'TATA VARANASI DELTA', 'Wipro GE Healthcare Private Limited'),
('SI_IMP1', 'TFS Contract - 230041', 'Bangalore International Airport Limited'),
('SI_AMC12', 'TIIC Fortinet renewal', 'THE TAMILNADU INVESTMENT CORPORATION LTD'),
('DC_IMP14', 'TPHQ - DC', 'Larsen & Toubro Limited (Telangana)'),
('DC_IMP6', 'TPHQ CCC', 'Larsen & Toubro Limited (Telangana)'),
('SI_O-M19', 'TPL Bharathnet SNOC Raipur O&M', 'TATA PROJECTS LIMITED'),
('MS_CLOUD7', 'Trivitron _ AWS Consumption - 240307', 'TRIVITRON HEALTH CARE'),
('CL_SUB_RE6', 'Trivitron Health Care', 'TRIVITRON HEALTH CARE'),
('SP_CON2', 'TRV- Consulting - 250117', 'AECOM India Private Limited'),
('DC_AMC3', 'University of Calicut(DC AMC)', 'University of Calicut'),
('SI_SUP63', 'Victora Hospi_Supply of Wi-Fi Indoor AP', 'VICTORA HOSPITALITIES PRIVATE LIMITED'),
('SI_SUP11', 'Visteon 9300 Switch Supply', 'VISTEON TECHNICAL AND SERVICES CENTRE PRIVATE LIMITED'),
('SI_SUP10', 'Visteon Supply', 'VISTEON TECHNICAL AND SERVICES CENTRE PRIVATE LIMITED'),
('SI_SUP55', 'Visteon Switch Supply', 'VISTEON TECHNICAL AND SERVICES CENTRE PRIVATE LIMITED'),
('SI_SUP33', 'Visteon Switches', 'VISTEON TECHNICAL AND SERVICES CENTRE PRIVATE LIMITED'),
('SI_SUP34', 'Vlink SFP module', 'V Link Systems (P) Ltd'),
('SI_SUP42', 'VM Ware License supply', 'Inspace Technologies (P) Ltd'),
('SI_SUP82', 'VMWARE VSPHERE 8 ESSENTIALS KIT', 'Inspace Technologies (P) Ltd'),
('CL_SUP11', 'VOICE SNAP SERVICES - VDI Solution', 'VOICE SNAP SERVICES PVT LTD'),
('CL_SUB_RE2', 'VOLUMEMAIL readylink.in -1 Year', 'Readylink Internet Services Limited'),
('MS_SUP16', 'Web Application protection', 'Karnataka Power Transmission Corp ltd'),
('MS_SUP6', 'Web Hosting Renewal', 'United Institute of Technology'),
('MS_SUP28', 'Web Hosting renewal for 1 year', 'United Institute of Technology'),
('MS_CLOUD5', 'Web Portal Migration to AWS Cloud', 'TRIVITRON HEALTH CARE'),
('MS_CLOUD4', 'Web Portal Migration to AWS Cloud', 'TRIVITRON HEALTH CARE'),
('SI_SUP22', 'WiFi Access Points & Switch supply', 'Amrita Vishwa Vidyapeetham(TN)'),
('CPSO622', 'WiFi AMC renewal for Aruba Stack-240425', 'Siemens Technology and Services Pvt Ltd.'),
('SI_IMP31', 'WIPRO GE HEALTH CARE_LAN Networking', 'Wipro GE Healthcare Private Limited'),
('SI_IMP42', 'Wipro GE Healthcare pvt ltd', 'Wipro GE Healthcare Private Limited'),
('DC_O-M1', 'Wipro GE(MCC DC O&M Support)', 'Wipro GE Healthcare Private Limited'),
('DC_O-M6', 'WIPRO GE(MCC DC/DR - 3 Yrs FMS Support)', 'Wipro GE Healthcare Private Limited'),
('DC_AMC2', 'Wipro GE(MCC DC/DR - AMC Support)', 'Wipro GE Healthcare Private Limited'),
('DC_AMC5', 'WIPRO GE(MCC DC/DR -CAMC Support)', 'Wipro GE Healthcare Private Limited'),
('SI_IMP44', 'Wipro-GE healthcare_UPS and cabling work', 'Wipro GE Healthcare Private Limited'),
('MS_SUP29', 'Zimbra Renewal - 240080', 'Lakshmi Card Clothing Mfg Company');
