



export const risksFormConfig = {
  fields: [
    { name: "risk_id", label: "Risk ID", type: "text", required: false, readOnly: true },
    { name: "manual_project_id", label: "Project ID", type: "project-search", required: true },
    { name: "account", label: "Account", type: "text", required: true, readOnly: true, placeholder: "Auto-generated" },
    { name: "project_description", label: "Project Description", type: "textarea", required: true, readOnly: true, placeholder: "Auto-generated" },
    { name: "risk_title", label: "Risk Title", type: "text", required: true },
    { name: "risk_description", label: "Risk Description", type: "textarea", required: true },
    { name: "identified_date", label: "Identified Date", type: "date", required: true },
    { name: "identified_by", label: "Identified By", type: "text", required: true },
    { name: "created_by", label: "Created By", type: "text", required: false, readOnly: true },
    { name: "created_at", label: "Created At", type: "text", required: false, readOnly: true },
    { name: "updated_at", label: "Updated At", type: "text", required: false, readOnly: true },
    {
      name: "status",
      label: "Status",
      type: "select",
      required: true,
      options: [
        "Open",
        "Resolved",
        "Cancelled",
      ],
    },
    {
      name: "priority",
      label: "Priority",
      type: "select",
      required: true,
      options: ["Critical", "High", "Medium", "Low"],
    },
    {
      name: "category",
      label: "Category",
      type: "select",
      required: true,
      options: ["Schedule", "Scope", "Technical", "Resource", "Security", "Operational"],
    },
    {
      name: "probability",
      label: "Probability",
      type: "select",
      required: true,
      options: ["Rare", "Possible", "Likely (Regularly)"],
    },
    {
      name: "impact",
      label: "Impact",
      type: "select",
      required: true,
      options: ["Minor", "Moderate", "Major"],
    },
    {
      name: "risk_score",
      label: "Risk Score",
      type: "text",
      required: false,
      readOnly: true,
    },
    { name: "mitigation_strategy", label: "Mitigation Strategy", type: "textarea", required: false },
    { name: "mitigation_owner", label: "Mitigation Owner", type: "text", required: false },
    { name: "target_mitigation_date", label: "Target Mitigation Date", type: "date", required: false },
    { name: "current_status", label: "Current Status", type: "textarea", required: false },
    { name: "last_reviewed_date", label: "Last Reviewed Date", type: "date", required: false },
  ],
};

export const issuesFormConfig = {
  fields: [
    { name: "issue_id", label: "Issue ID", type: "text", required: false, readOnly: true },
    { name: "manual_project_id", label: "Project ID", type: "project-search", required: true },
    { name: "account", label: "Account", type: "text", required: true, readOnly: true, placeholder: "Auto-generated" },
    { name: "project_description", label: "Project Description", type: "textarea", required: true, readOnly: true, placeholder: "Auto-generated" },
    { name: "issue_title", label: "Issue Title", type: "text", required: true },
    { name: "issue_description", label: "Issue Description", type: "textarea", required: true },
    { name: "reported_date", label: "Reported Date", type: "date", required: true },
    { name: "reported_by", label: "Reported By", type: "text", required: true },
    {
      name: "status",
      label: "Status",
      type: "select",
      required: true,
      options: ["Open", "Resolved", "Cancelled"],
    },
    {
      name: "priority",
      label: "Priority",
      type: "select",
      required: true,
      options: ["Critical", "High", "Medium", "Low"],
    },
    {
      name: "category",
      label: "Category",
      type: "select",
      required: true,
      options: ["Technical", "Operational", "Resource", "Infrastructure", "Application", "Network", "Security", "Performance"],
    },
    { name: "impact_on_project", label: "Impact on Project", type: "textarea", required: true },
    { name: "affected_system", label: "Affected System/Service", type: "text", required: true },
    { name: "assigned_to", label: "Assigned To", type: "text", required: true },
    { name: "target_resolution_date", label: "Target Resolution Date", type: "date", required: true },
    { name: "actual_resolution_date", label: "Actual Resolution Date", type: "date", required: false },
    { name: "resolution_details", label: "Resolution Details", type: "textarea", required: false },
    { name: "root_cause_analysis", label: "Root Cause Analysis", type: "textarea", required: false },
    { name: "last_updated", label: "Last Updated", type: "date", required: true },
  ],
};

export const actionsFormConfig = {
  fields: [
    { name: "action_id", label: "Action ID", type: "text", required: false, readOnly: true },
    { name: "manual_project_id", label: "Project ID", type: "project-search", required: true },
    { name: "account", label: "Account", type: "text", required: true, readOnly: true, placeholder: "Auto-generated" },
    { name: "project_description", label: "Project Description", type: "textarea", required: true, readOnly: true, placeholder: "Auto-generated" },
    { name: "action_title", label: "Action Title", type: "text", required: true },
    { name: "action_description", label: "Action Description", type: "textarea", required: true },
    { name: "created_date", label: "Created Date", type: "date", required: true },
    { name: "created_by", label: "Created By", type: "text", required: true },
    {
      name: "status",
      label: "Status",
      type: "select",
      required: true,
      options: [
        "Open",
        "Resolved",
        "Cancelled",
      ],
    },
    {
      name: "priority",
      label: "Priority",
      type: "select",
      required: true,
      options: ["Critical", "High", "Medium", "Low"],
    },
    { name: "action_owner", label: "Action Owner", type: "text", required: true },
    { name: "due_date", label: "Due Date", type: "date", required: true },
    { name: "completion_date", label: "Completion Date", type: "date", required: false },
    { name: "completion_percent", label: "Completion %", type: "text", required: false },

    {
      name: "related_to_type",
      label: "Related To Type (Risk/Issue)",
      type: "select",
      required: false,
      options: ["Risk", "Issue"],
    },
    {
      name: "related_to_id",
      label: "Related To ID",
      type: "text",
      required: false,
    },

    { name: "dependencies", label: "Dependencies", type: "textarea", required: false },
    { name: "last_updated", label: "Last Updated", type: "date", required: true },
  ],
};

export const dependenciesFormConfig = {
  fields: [
    { name: "dependency_id", label: "Dependency ID", type: "text", required: false, readOnly: true },
    { name: "manual_project_id", label: "Project ID", type: "project-search", required: true },
    { name: "account", label: "Account", type: "text", required: true, readOnly: true, placeholder: "Auto-generated" },
    { name: "project_description", label: "Project Description", type: "textarea", required: true, readOnly: true, placeholder: "Auto-generated" },
    { name: "dependency_title", label: "Dependency Title", type: "text", required: true },
    { name: "description", label: "Description", type: "textarea", required: true },
    { name: "reported_date", label: "Reported Date", type: "date", required: true },
    { name: "reported_by", label: "Reported By", type: "text", required: true },
    {
      name: "status",
      label: "Status",
      type: "select",
      required: true,
      options: [
        "Open",
        "Resolved",
        "Cancelled",
      ],
    },
    {
      name: "priority",
      label: "Priority",
      type: "select",
      required: true,
      options: ["Critical", "High", "Medium", "Low"],
    },
    {
      name: "type",
      label: "Type",
      type: "select",
      required: true,
      options: ["Internal", "External", "Vendor", "Client", "Cross-Team"],
    },
    {
      name: "dependent_on",
      label: "Dependent On (Team/Party)",
      type: "text",
      required: true,
    },
    {
      name: "impact_if_not_resolved",
      label: "Impact if Not Resolved",
      type: "textarea",
      required: true,
    },
    { name: "required_by_date", label: "Required By Date", type: "date", required: true },
    { name: "current_status", label: "Current Status", type: "textarea", required: false },
    { name: "follow_up_date", label: "Follow-up Date", type: "date", required: false },
    { name: "contact_person", label: "Contact Person", type: "text", required: false },
    { name: "contact_details", label: "Contact Details", type: "text", required: false },
    { name: "last_updated", label: "Last Updated", type: "date", required: true },
  ],
};

export const escalationsFormConfig = {
  fields: [
    { name: "escalation_id", label: "Escalation ID", type: "text", required: false, readOnly: true },
    { name: "manual_project_id", label: "Project ID", type: "project-search", required: true },
    { name: "account", label: "Account", type: "text", required: true, readOnly: true, placeholder: "Auto-generated" },
    { name: "project_description", label: "Project Description", type: "textarea", required: true, readOnly: true, placeholder: "Auto-generated" },
    { name: "title", label: "Title", type: "text", required: true },
    { name: "description", label: "Description", type: "textarea", required: true },
    { name: "reported_date", label: "Reported Date", type: "date", required: true },
    { name: "reported_by", label: "Reported By", type: "text", required: true },
    {
      name: "status",
      label: "Status",
      type: "select",
      required: true,
      options: [
        "Open",
        "Resolved",
        "Cancelled",
      ],
    },
    {
      name: "priority",
      label: "Priority",
      type: "select",
      required: true,
      options: ["Critical", "High", "Medium", "Low"],
    },
    {
      name: "category",
      label: "Category",
      type: "select",
      required: true,
      options: [
        "Performance",
        "Availability",
        "Security",
        "Quality",
        "Communication",
        "Resource",
        "Budget",
        "Scope",
      ],
    },
    { name: "impact", label: "Impact", type: "textarea", required: true },
    { name: "customer_name", label: "Customer Name", type: "text", required: false },
    { name: "escalated_to", label: "Escalated To", type: "text", required: false },
    {
      name: "target_resolution_date",
      label: "Target Resolution Date",
      type: "date",
      required: true,
    },
    {
      name: "actual_resolution_date",
      label: "Actual Resolution Date",
      type: "date",
      required: false,
    },
    { name: "resolution_details", label: "Resolution Details", type: "textarea", required: false },
    { name: "root_cause", label: "Root Cause", type: "textarea", required: false },
    { name: "preventive_actions", label: "Preventive Actions", type: "textarea", required: false },
    { name: "last_updated", label: "Last Updated", type: "date", required: true },
  ],
};

export const appreciationsFormConfig = {
  fields: [
    { name: "appreciation_id", label: "Appreciation ID", type: "text", required: false, readOnly: true },
    { name: "manual_project_id", label: "Project ID", type: "project-search", required: true },
    { name: "account", label: "Account", type: "text", required: true, readOnly: true, placeholder: "Auto-generated" },
    { name: "project_description", label: "Project Description", type: "textarea", required: true, readOnly: true, placeholder: "Auto-generated" },
    { name: "subject", label: "Subject", type: "text", required: true },
    { name: "details", label: "Details", type: "textarea", required: true },
    { name: "received_date", label: "Received Date", type: "date", required: true },
    { name: "recorded_by", label: "Recorded By", type: "text", required: true },
    { name: "customer_name", label: "Customer Name", type: "text", required: true },
    { name: "customer_contact", label: "Customer Contact", type: "text", required: false },
    {
      name: "appreciation_type",
      label: "Appreciation Type",
      type: "select",
      required: true,
      options: ["Email", "Call", "Meeting", "Formal Letter", "Survey Feedback", "Verbal"],
    },
    {
      name: "team_members_recognized",
      label: "Team Members Recognized",
      type: "textarea",
      required: false,
    },
    {
      name: "shared_with_team",
      label: "Shared with Team",
      type: "select",
      required: true,
      options: ["Yes", "No"],
    },
    { name: "follow_up_action", label: "Follow-up Action", type: "textarea", required: false },
    { name: "last_updated", label: "Last Updated", type: "date", required: true },
  ],
};


